### ISSUE TITLE
cannot add a group

### ISSUE THREAD

**Issue by chrismaes87** [antelle/keeweb#1]
Hi,

The interface works fine for browsing; but I cannot add a new group. Clicking "+" and selecting group doesn't do anything.

Chris.

**Comment by antelle** [comment]
https://github.com/antelle/keeweb/blob/master/TODO.md#mvp

**Comment by antelle** [comment]
This will be implemented soon...

**Comment by chrismaes87** [comment]
ok sorry. Nice implementation though.

**Comment by antelle** [comment]
So I've finished the implementation. Now groups can be added and edited.
