### ISSUE TITLE
KeePass 1/2 compatibility

### ISSUE THREAD

**Issue by holgerd77** [antelle/keeweb#102]
Hi, could you add a note on Keepass DB version 1 and/or 2 compatibility in the README? Cool, this looks really great!

**Comment by phsc** [comment]
This is already mentioned in the [FAQ](https://github.com/antelle/keeweb/wiki/FAQ#compatibility), and the FAQ are mentioned in the README.

**Comment by holgerd77** [comment]
Ok, thanks!
