### ISSUE TITLE
Don't use Math.random to generate passwords

### ISSUE THREAD

**Issue by lorenzhs** [antelle/keeweb#104]
`Math.random()` is unsafe for cryptographic purposes, it should definitely not be used to generate passwords!  It seems that [the library function](https://github.com/antelle/keeweb/blob/8bc020c5b03d1db67483b510ca7e403615a0e642/app/scripts/util/password-generator.js#L25) in your kdbx library [combines it with some Salsa20](https://github.com/antelle/kdbxweb/blob/906e927d3e3384db4dd393f6a9cbba00b1c85720/lib/crypto/random.js#L14) but that's not enough.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random):
> **Note:** `Math.random()` does not provide cryptographically secure random numbers. Do not use them for anything related to security. Use the Web Crypto API instead, and more precisely the `window.crypto.getRandomValues()` method.

You should fix this immediately.

**Comment by lorenzhs** [comment]
Ah, it seems that there is a similar issue in the kdbxweb repo already: https://github.com/antelle/kdbxweb/issues/5

**Comment by antelle** [comment]
It's combined with pseudo-random sequence with random seed, so there's no urgent serious security issue for now. Thanks, it will be replaced in the next version.

**Comment by floriangosse** [comment]
Maybe we can use https://github.com/ckknight/random-js for *real* random values.

**Comment by lorenzhs** [comment]
No just use `window.crypto.getRandomValues()` which is specifically designed to be cryptographically secure.  It's also provided by the browser and not an additional dependency.

**Comment by dchest** [comment]
There's also modulo bias in password generator, although it's less important than using `Math.random`. Feel free to use this module: https://gist.github.com/dchest/751fd00ee417c947c252 to generate uniform random strings in password generator.

**Comment by antelle** [comment]
So, I've fixed it in https://github.com/antelle/kdbxweb/commit/b274e5da44241c6a61af0ebf48bc83f933b76ca5
Now random values will be generated by `crypto.getRandomValues XOR salsa20`, XORing is added to prevent backdoors in _recommended_ functions.
Will be available in the next release.
