### ISSUE TITLE
[Feature Request] Google Drive Support

### ISSUE THREAD

**Issue by evenicoulddoit** [antelle/keeweb#105]
Would be awesome if you added Google Drive support as that's where I sync my DB to/from.

**Comment by phsc** [comment]
Already mentioned in ticket #14, so more or less a duplicate.

**Comment by evenicoulddoit** [comment]
Sorry, searched for an existing Google Drive request but didn't find out. Happy to close but I think the body of work would be separate

**Comment by antelle** [comment]
I'll leave it open for now but yes it's a diplicate of #14 and implementation is planned for v1.1

**Comment by antelle** [comment]
Google drive support implemented on https://beta.keeweb.info

**Comment by andreimarcu** [comment]
How does it work?

**Comment by antelle** [comment]
@andreimarcu  more &rarr; settings &rarr; scroll to bottom &rarr; check google drive &rarr; google drive
I'll enable it by default soon
