### ISSUE TITLE
[Feature Request] OneDrive Support

### ISSUE THREAD

**Issue by wenLiangcan** [antelle/keeweb#106]
I'm using the KeePass official app with [KeePassOneDriveSync](https://github.com/KoenZomers/KeePassOneDriveSync) plugin on Windows. But most of the time I work on Linux and that plugin doesn't support Linux. It would be nice if keeweb can add OneDrive support as a cross platform application.

**Comment by KapuzenSohn** [comment]
Look at #14

**Comment by antelle** [comment]
duplicate of #14
