### ISSUE TITLE
Can`t open db file created by KeePassX (OS X)

### ISSUE THREAD

**Issue by bmatej** [antelle/keeweb#109]
The file db, that was created by KeePassX can`t be opened on OS X. When I choose the file db, the file db is not beeing displayed in list like in windows version.
When I try to enter password, that is working on KeePassX, the input bar goes red and nothing else happens.

**Comment by antelle** [comment]
Hello,
- Which version of keeweb are you using: web or desktop?
- What is the version of KeePassX?
- If it's a fresh db, please attach it to this issue, I'll take a look.

The app can open KeePassX databases, it was tested several times and there are some users working both with KeePassX and KeeWeb without troubles.

**Comment by lambdaupb** [comment]
I have the same Issue with a KeePassX version 1 DB. I assume this is a general limitation.

**Comment by antelle** [comment]
KDB is not supported, and there'are no plans to support it. It's mentioned in [FAQ](https://github.com/antelle/keeweb/wiki/FAQ#compatibility).

**Comment by antelle** [comment]
So assuming that @bmatej means v1 format (KDB), I'm closing it. Please reopen in case of any issues with kdbX (v2).
