### ISSUE TITLE
Can create a group without name

### ISSUE THREAD

**Issue by antelle** [antelle/keeweb#11]
Such groups should have '(no title)' name, or just don't allow to create them - decide.

**Comment by 4ndv** [comment]
In keepass i can create groups and entries without name, it is really bug?
Maybe just make a whole item clickable, except only title?

**Comment by antelle** [comment]
Maybe you're right, in that case we should write (no title) instead. I'll see how it's made in keepass.

**Comment by antelle** [comment]
So, I made a decision to disallow this as groups without a title make no sense, and fixed errors on creation and display. However such groups are supported in format, so they will be displayed as `(no title)` and fully functional, as other groups.
