### ISSUE TITLE
Numbers rendered as unicode placeholders in Chrome Windows

### ISSUE THREAD

**Issue by MrP** [antelle/keeweb#110]
This is  chrome bug, actually:

https://bugs.chromium.org/p/chromium/issues/detail?id=583216&q=pnum&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

So, of course, feel free to close this issue, just wanted to make sure you were aware of it in case you didn't know, and want to mitigate while Chrome fixes it.

The offending CSS declaration appears to be:
body {
...
    font-feature-settings: "kern","liga", "pnum";
}

Particularly the "pnum" bit.

This is a great project, just what I needed!  Good job

**Comment by MrP** [comment]
![numbers](https://cloud.githubusercontent.com/assets/31433/13333470/20e44f2a-dbff-11e5-8958-84ca955df4fd.png)

**Comment by antelle** [comment]
Thanks for letting me know! Of course, I'll add a workaround. But how this actually could be repeated? I've just tried Chrome 48 on Windows 10:
![windows 10 running 2016-02-25 23-39-43](https://cloud.githubusercontent.com/assets/633557/13333689/4282d9c0-dc19-11e5-874c-0f5282661b1a.png)

**Comment by MrP** [comment]
Version 48.0.2564.116 m on Windows 10.

I tried also in Firefox on the same machine, and it was fine, FWIW

I'll test a bit more.  Could it be an "installed fonts" thing?

**Comment by antelle** [comment]
From this comment https://bugs.chromium.org/p/chromium/issues/detail?id=583216#c2
> font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif
Looks like a shaping font fallback failure.

So, do you have Helvetica font installed?

**Comment by antelle** [comment]
Also, could you please test disabling on your Chrome devtools `font-feature-settings: "kern","liga", "pnum";`, specifically `pnum`?

**Comment by MrP** [comment]
Yes, deleting "pnum" fixes it.

In my Windows/fonts fodler I have no Helvetica file.  I have no idea if there's any other place to check...

**Comment by antelle** [comment]
Perfect, thank you. I've added this and deployed to https://beta.keeweb.info - please let me know if it works ok for you.

**Comment by MrP** [comment]
In beta it's fine:

![betanumbers](https://cloud.githubusercontent.com/assets/31433/13334110/38372208-dc02-11e5-955e-5b4b460ec068.png)

I tried also playing with the font-family declaration, and it didn't matter, all fonts seemed to be affected.  It may be one of those things...

**Comment by antelle** [comment]
Great! I'll merge to stable and update the app shortly.

**Comment by MrP** [comment]
Nice, thanks!

**Comment by antelle** [comment]
The update has arrived
