### ISSUE TITLE
Reference domain is vulnerable to MITM attacks

### ISSUE THREAD

**Issue by eligrey** [antelle/keeweb#111]
In [this comment](https://github.com/antelle/keeweb/issues/76#issuecomment-178703271), you state that you only got HTTPS through CloudFlare. I also have noticed that you are hosting this app with GitHub pages. This implies that there is an unvalidated TLS connection between GitHub pages and CloudFlare.

To resolve this issue, complete the following checklist:

- [ ] Host app.keeweb.info using something other than GitHub pages.
- [ ] Get a TLS certificate for app.keeweb.info. [Let's Encrypt](https://letsencrypt.org/) certificates are free.
- [ ] Enable HSTS and HPKP.
- [ ] Either change your [CloudFlare crypto settings](https://www.cloudflare.com/a/crypto/keeweb.info) to "Strict" or directly serve the website without using the CloudFlare proxy.

and/or (less secure alternative that's better than doing nothing)

- [ ] Enable DNSSEC for keeweb.info, to make it a little more difficult to MITM connections with spoofed DNS.

**Comment by antelle** [comment]
MITM attacker must be between CloudFlare and GitHub pages, not between the user and server. I could not event imagine, how is that possible, as CloudFlare doesn't provide script access to their hosting and they are not executing users code. As GitHub pages. However if there's a way to make it with completely free tools (free as in beer), I could do this, I'll investigate.

**Comment by eligrey** [comment]
> I could not event imagine, how is that possible, as CloudFlare doesn't provide script access to their hosting and they are not executing users code

They don't need to execute anything. All that needs to happen is for your nameservers to be spoofed (which is difficult for many but easily possible by tier 1 network operators) as you do not have DNSSEC enabled.

> However if there's a way to make it with completely free tools (free as in beer), I could do this, I'll investigate.

The only mitigation available if you wish to continue using GitHub pages is the last checkbox (enable DNSSEC). CloudFlare supports DNSSEC so the setup should be easy enough as long as your registrar supports it. This will essentially fix this vulnerability and you can close this issue once you have DNSSEC enabled.

You can verify your DNSSEC records at http://dnssec-debugger.verisignlabs.com/keeweb.info

**Comment by antelle** [comment]
DNSSEC makes sense, I've submitted a ticket about DNSSEC to the registrar, so it should be enabled shortly. I'll try to research hosting options: I'm not particular about GitHub pages but I have to find a free hosting US-located hosting which provides custom certificates.

**Comment by antelle** [comment]
DNSSEC is here

**Comment by SamuelePilleri** [comment]
It is now possible to bypass Cloudflare entirely: [Custom domains on GitHub Pages gain support for HTTPS](https://github.blog/2018-05-01-github-pages-custom-domains-https/).

**Comment by antelle** [comment]
Nice, we should move there, however we’ll have to do something with certificate pinning.

**Comment by SamuelePilleri** [comment]
HPKP is on its way to be deprecated; please see https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning#Browser_support_and_deprecation


I've searched, but have been unable to find any official statement on whether Github Pages with custom domain and enforced HTTPS makes use of HSTS or Expect-CT.

**Comment by antelle** [comment]
@SamuelePilleri sorry I meant HSTS, not HPKP. So, existing users who already have received the policy will be stuck. And it's not supported on GitHub pages yet: https://github.com/isaacs/github/issues/1249

**Comment by antelle** [comment]
Headers from GitHub pages:
```
curl https://192.30.252.153 --header 'Host: app.keeweb.info' -o /dev/null --dump-header - -k -s

HTTP/1.1 200 OK
Server: GitHub.com
Date: Tue, 20 Aug 2019 18:01:53 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 1341913
Vary: Accept-Encoding
Last-Modified: Mon, 19 Aug 2019 19:20:18 GMT
Vary: Accept-Encoding
ETag: "5d5af672-1479d9"
Access-Control-Allow-Origin: *
Expires: Tue, 20 Aug 2019 18:11:53 GMT
Cache-Control: max-age=600
Accept-Ranges: bytes
X-Proxy-Cache: MISS
X-GitHub-Request-Id: 7BD9:4317:30C57:3C974:5D5C3591
```

So, not now... Let's wait a bit until it's better.

**Comment by SamuelePilleri** [comment]
I'm not sure where that IP address comes from. "Newer" Github Pages websites are server from another CDN (powered by Fastly AFAIK) and newer IPs are listed here: https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider Please note that this feature was shipped in May, 2018 and there's no roadmap for future improvements which will likely roll out quietly.

**Comment by antelle** [comment]
That's GitHub's pages IP. Just tried CDN, got same results.

**Comment by SamuelePilleri** [comment]
Netlify may be the "free US-located hosting" provider that you were looking for. Also, it does support HSTS today: https://www.netlify.com/docs/ssl/#hsts-preload

From a security perspective, I would prefer to have to deal with a single organization (Github in this case), but this could be a step forward. Please consider if it can accomodate the needs of this project.

**Comment by antelle** [comment]
If they support HSTS, yes, it will be possible to use it. Until then – no, the site won't even open because it's in the lost of sites with mandatory HSTS.

**Comment by SamuelePilleri** [comment]
Their docs state that it is supported, however I would suggest looking carefully if it can work for you. Also their service integrates with Github and you wouldn't have to manually build your web application every time. Thank you for interesting on this.

**Comment by antelle** [comment]
I meant GitHub. For Netlify, the traffic limitation 100GB per month is quite strict, we're quite close to it now and of course I'm not going to pay $45 / month for a free project.

**Comment by antelle** [comment]
By the way, as GitHub supports HTTPS now, we'll be able to use full (strict) SSL, I'll try it out on another domain and will configure it here as well if it works, so this will solve the issue.

**Comment by SamuelePilleri** [comment]
While testing on the other domain, could you please see if the "Enforce HTTPS" option has any effect on HSTS? For reference: https://github.blog/2018-05-01-github-pages-custom-domains-https/ Thank you.

**Comment by antelle** [comment]
That's the problem, it's disabled because HTTPS is not enabled for my domain at all. Looks like GitHub enables it only if you change DNS to GitHub's servers. That's what I would like to check on another domain.

**Comment by antelle** [comment]
Just checked it: no, unfortunately, it doesn't enable HSTS.

**Comment by antelle** [comment]
So I tried it on another domain and it looks like, we can enable Full (Strict) mode in CloudFlare now (but let's it a couple of days to make sure it doesn't break), however it requires changing the DNS to GitHub first, so some downtime is expected. The transition looks like this:

1. change DNS to GitHub (this way GitHub understands that it can enable HTTPS now)
2. update the website
3. wait until it's activated
4. enable HTTPS-only
5. change it back to CloudFlare
6. enable Full (Strict)

**Comment by antelle** [comment]
I extracted the plan here: https://github.com/keeweb/keeweb/issues/1247
Unfortunately I have to take down the website for several hours to be able to execute it, but after this we'll be able to use strict HTTPS on CloudFlare.

**Comment by SamuelePilleri** [comment]
Thank you for taking care of this, much appreciated! Let's hope Github Pages will start offering HSTS sometime soon, so it will be possible to bypass Cloudflare entirely.

**Comment by antelle** [comment]
I guess, when they implement it in a year or so, it already won't be possible, because GitHum has 100GB / month bandwidth limitation.

**Comment by SamuelePilleri** [comment]
Yeah I just saw your addition to your previous message, too bad Github Pages has that limitation too.

I never so such a dashboard on the repo owner's end, how are users supposed to know whether their site is close to that limit or not?

**Comment by antelle** [comment]
I guess, there's a sort of mail that is sent when the consumed bandwidth is close to 100GB or over it, after this if there's no reaction from the author for some time, they hard-limit it or shut down the website completely. At least that's how soft limit is usually implemented.

Regarding KeeWeb, I can see upstream traffic in CloudFlare, it's around 10G now.

**Comment by antelle** [comment]
Hm, looks like GitHub checks if DNS is pointing to GitHub servers and revokes certificates if not 😕 
This happened to another website just now, after a couple of days I updated the settings. That's quite bad, it means we won't be able to update this setting.
