### ISSUE TITLE
Password being truncated?

### ISSUE THREAD

**Issue by renatomassaro** [antelle/keeweb#113]
When I create a new database and set a long password (1024+ chars), it won't work.

Steps to reproduce:
- create new db
- set master password to a long password
- (no key file set)
- sync with dropbox (did not test locally)
- logout
- try to login with same password
- login fails

I tried 128, 1024 and 2048-characters long passwords. The 128 one worked fine but both 1024 and 2048 failed. Anyone else can confirm?

KeeWeb v1.0.4 (a6e7afe, 2016-02-25)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by antelle** [comment]
Sorry, 1024-symbols passwords are not for people.

**Comment by renatomassaro** [comment]
Such argument. See, there is a valid use case for longer passwords, but I respect your decision not to fix it.

> File format should be 100% compatible but I test integration with KeePass only. Other clients should be ok, if not, please, open an issue and it will be fixed. Only kdbx (KeePass v2), not kdb (KeePass v1) is supported.

So there, you can claim that its 99% compatible now, since kdbx with long master keys won't work.

**Comment by antelle** [comment]
I don't see any use case except automation tasks. It cannot affect regular users, as typing 1024-symbol password is impossible.
> with long master keys

With long passwords. Master keys stored in keyfiles will work.
I'll paraphrase that sentence today, to emphasize that features related to humans are supported, not automation, or just testing max password length for fun.

**Comment by smacleod** [comment]
I have also hit this password length bug - my password is not 1024 characters, but it is a reasonably long passphrase that I type. I am also human.

Do you have a technical reason for limiting the password length, or is this just an arbitrary decision?

**Comment by antelle** [comment]
@smacleod if it's not so long, it's another bug, please don't post it in this issue. what's there in the error log?

**Comment by smacleod** [comment]
It is greater than 128 characters in length, but less than 1024. The devtools are indicating the password box is maxed at 128 characters, so yes I believe it is this bug.

Log:
016-05-21T17:40:41.608Z [file] Error opening file InvalidKey Error InvalidKey KdbxError {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey"}
c.error @ index.html:14
(anonymous function) @ index.html:16
(anonymous function) @ index.html:7
(anonymous function) @ index.html:8
index.html:14
2016-05-21T17:40:41.612Z [open-view] Error opening file KdbxError {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey"}
c.error @ index.html:14
e.View.extend.openDbComplete @ index.html:21
(anonymous function) @ index.html:17
(anonymous function) @ index.html:16
(anonymous function) @ index.html:7
(anonymous function) @ index.html:8

**Comment by antelle** [comment]
In next version it will be possible to open a db with such password. Sure 128 is not enough.

**Comment by smacleod** [comment]
There were a couple places missing in your fix, I've submitted a pull request which I tested locally with my longer password.
