### ISSUE TITLE
Unable to unlock keepass file

### ISSUE THREAD

**Issue by peterloron** [antelle/keeweb#114]
We have an existing KeePass 3 file which I can unlock using both KeePass as well as Loxodo. When I try to load the same file and unlock it with keeweb, I get a brief activity spinner, and then the password box turns red. This is on a OS X 10.10.5 machine.

Is there any way to turn on debug logging so we can see what is going wrong?

Thanks.

**Comment by renatomassaro** [comment]
May be related to #113

**Comment by peterloron** [comment]
@renatomassaro Unlikley. The password for the file is pretty short, just 11 chars.

**Comment by antelle** [comment]
Please, paste error log from dev console. If you are using desktop version, dev console can be found in Settings/Advanced.

**Comment by vdolbilov** [comment]
Hi there, I have a similar problem. Have a .kdb file that can be opened by KeePassX as well as MacPass. This is the error from the web version.

```
2016-02-26T16:11:51.680Z [file] Error opening file KdbxError {name: "KdbxError", code: "BadSignature", message: "Error BadSignature"} BadSignature Error BadSignature KdbxError {name: "KdbxError", code: "BadSignature", message: "Error BadSignature"}c.error @ (index):13d.Model.extend.open @ (index):14d.Model.extend.openFileWithData @ (index):15d.Model.extend.openFile @ (index):15
(index):13
2016-02-26T16:11:51.681Z [open-view] Error opening file KdbxError {name: "KdbxError", code: "BadSignature", message: "Error BadSignature"}
```

Or does this app only work with .kdbx databases? What's the difference?

**Comment by antelle** [comment]
> Or does this app only work with .kdbx databases?

Exactly. Only KDBX are supported, this is mentioned in FAQ, and as it's a frequent question, I'll add a warning to the app, containing description how to convert to KDBX.

> What's the difference?

KDB and KDBX are completely different formats: v1 (KDB) is binary and considered obsolete, v2 (KDBX) is xml and generally more advanced. There are no plans to support KDB.

**Comment by antelle** [comment]
Closing until more info is provided, feel free to reopen with error logs.

**Comment by marcopatr** [comment]
Hi! I beg your pardon, for I am sure that the answer/description can be found somewhere, unfortunately I could not find it.  

> containing description how to convert to KDBX

I need the main file in XML format and wanted to create it by using Keepass. When I rename the Keeweeb backup file to kdbx and then try to open it with Keepass, Keepass asks for a master password, a key file and the Windows user account. Since I don't use a master password or a key file, I leave this fields blank. But no matter if I click on Windows User Account or not, I still can't open the key file.

**Comment by antelle** [comment]
@marcopatr if you add a master password, you will be able to open it in KeePass.

**Comment by marcopatr** [comment]
Great! Thx for fast response!
