### ISSUE TITLE
[Feature Request] Synchronize with local file

### ISSUE THREAD

**Issue by gramasaurous** [antelle/keeweb#117]
KeePass has the ability to synchronize the current database with other local files, which would be a nice feature. This is helpful if you like to keep your database backed up across different physical locations (USB or network drive backups).

**Comment by antelle** [comment]
Open the db in app, replace the file with a version from another device, save - it should be merged.
Please be careful! There might be strange bugs, don't forget about backups (but should not be), in case of any post an issue.
Or, you can use Dropbox: changes in it are merged as well.
Merging with another DB (really another, not this modified on another device) is not implemented and will result in error.
