### ISSUE TITLE
Unable to unlock databases with empty passwords

### ISSUE THREAD

**Issue by wohlben** [antelle/keeweb#119]
I'm unable to unlock keepass2 databases that are only secured with a passfile (no password)

**Comment by antelle** [comment]
Bad thing that KeePass distinguishes between _no password_ and _empty password_. Definitely we'll not support it and if the user has specified empty password, we'll have to try twice: with empty password and no password. I've just added support and tests in core reader library, v1.1 will support opening such files.

**Comment by antelle** [comment]
Fixed, it will appear in v1.1. I've tested it on files with empty password and no password, both with or without keyfile. You can preview is on https://beta.keeweb.info/ to check if it works for you.

**Comment by homhom1416** [comment]
> Fixed, it will appear in v1.1. I've tested it on files with empty password and no password, both with or without keyfile. You can preview it on https://beta.keeweb.info/ to check if it works for you.

It's look like not working any more .. 
KDBX3 or 4 with Empty password and keyfile .. saved from keepassXC or keepass .

**Comment by antelle** [comment]
Hi! Do you mean "empty keyfile" or "empty password + keyfile"?

**Comment by homhom1416** [comment]
I mean "empty password + a keyfile" .. i have a KDBX 3.1 file which was created by keepass with "empty password + a keyfile" and i can open it with keepassXC but i cannot open it with keeweb which say red rectangle wrong password ..
i saved database agian with keepassXC as KDBX 4 .. same issue .. but if i save a new empty database from keeweb with "empty password + a keyfile" works fine ,,!

**Comment by antelle** [comment]
Can you please make a new file similar to that one and attach it here? It worked for me

**Comment by homhom1416** [comment]
After a lot of tests the problem was clearly with my keyfile which was not automatically generated .. i generated it manually a long time ago .. i don't remember how .. 
The problem appear if i used it for any database ..
Just changing it everything fine ..
And vice versa if i used this keyfile with new database created with keeweb then this new database will opend with keeweb but will not opened with keepass and keepassXC also  ..! strange ..!
I don't know if it's okey to share my keyfile ..

**Comment by homhom1416** [comment]
This is my keyfile which i used ..
Use it for new database with keepass or keepassxc and then try open it with keeweb ..
Or use it for new database with keeweb and then try open it with keepassxc or keepass ..

[kpsrmhmt.txt](https://github.com/keeweb/keeweb/files/7202083/kpsrmhmt.txt)

**Comment by antelle** [comment]
I assume, it's because it's an old-format text keyfile. It's recommended to generate XML keyfiles for better compatibility.
