### ISSUE TITLE
Cannot edit fields in entries without name

### ISSUE THREAD

**Issue by 4ndv** [antelle/keeweb#12]
I create new entry, press tab, and entry disappears! :)
In keepass i can create entry without title, btw.
Possible solution: Highlight title with red and not delete entry instantly.

**Comment by antelle** [comment]
This was done for this case: create entry - oops! what have I made?77 ESC! - it should disappear. I agree, tab should create an entry without title, thanks.

**Comment by 4ndv** [comment]
Not too easy to accidentally create an entry :D

**Comment by antelle** [comment]
Editing entries without title (unlike groups) sometimes could be helpful (like, creating just a password), so I made it available. Thanks.
