### ISSUE TITLE
Can't open .kdbx file with orther clients

### ISSUE THREAD

**Issue by saponace** [antelle/keeweb#127]
Hi,

I don't see this issue anywhere and I'm surprised of that, I hope it is not me doing it wrong :)

I am actually using the webapp I deployed on my server.
To deploy the application, I did : `npm install ; grunt` 
Then serve the file keeweb/dist/index.html with my nginx server.

When I save any database with keeweb (button "save to file" in the database config menu) to a .kdbx file I am unable to open it with another keepass client.
I always have the error 
> Failed to open the specified file!
> Unexpected XML declaration. The XML declaration must be the first node in the document, and no whitespace characters are allowed to appear before it. Line 1 position 4.

Or 
> XML declaration cannot appear in this state, line 1 position 57.

Or any other similar error message depending on the client I use.

This error appear when I try to open any database that come from keeweb, even the demo and file that I imported from another keepass client and modified with keeweb.

The keeweb webapp you hosted on your server works flawlessly of course.

I used the Linux clients Keepass and Keepassx (from the Arch community repo) and the android clients KeePassDroid and Keepass2Android.

Thanks for your work anyways, your project looks promising !

**Comment by antelle** [comment]
Hello!
> The keeweb webapp you hosted on your server works flawlessly of course.

You mean, my app at app.keeweb.info can open such files (produced by your version), or it generated files which can be opened by other KeePass clients?

Does the problem repeat if you just deploy index.html file from gh-pages branch, without building?

**Comment by antelle** [comment]
Please also copy the output of following commands:
`npm list --depth 0`
`bower list`

**Comment by antelle** [comment]
I've just tested the installation on a fresh system and I confirm that the the issue exists. Some of npm packages was broken, I'll figure it out and upgrade or downgrage it.

**Comment by antelle** [comment]
Here's why: https://github.com/kangax/html-minifier/issues/513
I'll add a peerDependency shortly

**Comment by saponace** [comment]
Wow, that was quick ! 
Cheers mate !
