### ISSUE TITLE
Increase maximum generated password length

### ISSUE THREAD

**Issue by jamie-lord** [antelle/keeweb#13]
Currently the maximum generated password length is only 32 characters. Could this please be increased to at least 64 for those of us who like a really long password?

**Comment by antelle** [comment]
This will have negative impace on UX for the vast majority of users as the slider will move way too fast between 0 and 32.
The dialog should have advanced mode for such cases, where maybe it will offer even more options like passwords list and exclusion chars - not for everyday use. Adding to Future...

**Comment by antelle** [comment]
As a possible solution, slider values could be in this sequence: 3 - 4 - 5 - 6 - ... - 28 - 30 - 32 - 48 - 64 
Needs investigation, I'll try to check whether it's a reasonable solution

**Comment by jamie-lord** [comment]
No worries, it's clearly not urgent. Keep up the great work, this project seriously has the potential to not only convert existing KeePass users but also entice new users to this system. :smile:

**Comment by antelle** [comment]
So, I've fixed it, and in v2.x release password length step will now increase in a sort of logarithmic way (3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,24,26,28,30,32,48,64), and it will be possible to create 64-symbol password. Thanks.
![keeweb 2015-11-04 22-32-52](https://cloud.githubusercontent.com/assets/633557/10949484/28402bd6-8344-11e5-9cc7-8f6570c886f9.png)

**Comment by jamie-lord** [comment]
That's fantastic, thank you. Keep up the great work, this project's looking really good! :smile:
