### ISSUE TITLE
Shouldn't need to reselect keyfile when re-unlocking DB.

### ISSUE THREAD

**Issue by jimhawkridge** [antelle/keeweb#137]
- Open a database that is encrypted with a password and key file.
- Lock the database
- In order to unlock you now need to select the key file from the filesystem as well as enter the password.

I don't think there is any additional security in having to reselect the key file and it significantly slows down the process of getting a password out of the database.

**Comment by antelle** [comment]
option to remember keyfiles was already added and will be released in v1.1. https://github.com/antelle/keeweb/wiki/TODO#v11
You can preview this feature at https://beta.keeweb.info

**Comment by jimhawkridge** [comment]
Thanks, I didn't notice that in the TODO.

**Comment by rmmcnulty9** [comment]
Is there an estimated release date for v1.1? This is a huge pain having to enter my key file every time and I prefer using the desktop app. Thanks!

**Comment by antelle** [comment]
Just merged it and uploaded the release. Please click Update button in app settings.

**Comment by rmmcnulty9** [comment]
Awesome that was fast, thanks!

One additional thing, there doesn't appear to be any indication that a key file is being remembered when you are unlocking a DB. I was expecting it to show the key file name the same way it does after selecting one from the file system.

**Comment by antelle** [comment]
Hm, yes, thanks, I'll add an indication in the next release: `keyfile` title should be replaced actual keyfile name (e.g. my-db-key.key).

**Comment by antelle** [comment]
Added keyfile display, will be in the upcoming hotfix.
