### ISSUE TITLE
[Unconfirmed] Sometimes autosave error occurs for new files

### ISSUE THREAD

**Issue by antelle** [antelle/keeweb#140]
This is from user report: needs verification and reproduction, if you have the same issue, please let me know and (:exclamation:)  gather the logs once it occurred.

The description was as follows:
- so I first opened my existing Keepass database
- then pressed open/new at bottom of window
- then hit NEW
- Then went into settings and set the master password (no key file) and changed the name to [name_was_here_removed]
- I then added about 6 entries and went to exit in the bottom right corner of the app, which is when there was an autosave error
- went to settings and tried to save manually, I now remember seeing a line of text pop up to the right of  "Master password" but I don't remember what it said unfortunately.

v1.0.x, mac os x desktop

**Comment by kasoban** [comment]
Could not reproduce this, *but* when I follow the steps the database is saved locally in the app, containing NO entries (although some where added in the process).

**Comment by antelle** [comment]
are you sure you were adding records in the new db, not previously opened one? to add a record into a new db, you should select this db in the left list first.

**Comment by kasoban** [comment]
Ah, you are right. I didn't notice because I created 2 new databases for this test instead of starting with a persistent one. I expected the selection to work via the last selected DB on the bottom bar.

**Comment by antelle** [comment]
It's a confusing part, I'm still thinking how to make db selection more convenient: maybe in drop-down we should have several items: 'New in Private', 'New in Another', ... Not sure yet.

**Comment by isbad** [comment]
Could not reproduce as well

> how to make db selection more convenient

Just some thoughts: 
- to know where you are highlighting db name (bottom left corner) could be useful
- is it really important to open db settings by clicking its name (maybe db change much more frequent event) ?

**Comment by antelle** [comment]
The main idea is that DBs are not tabs, like in KeePass: you always work with all of them at once, unless you have filter by one of them intentionally - so db selection will break this idea. Setting filter by db selected in bottom is unacceptable as well, as this will be very confusing.

**Comment by isbad** [comment]
Got it. What do you think: 
- keep "new entry" simple and fast
- default behavoir is necessarily (most used db) 
- need to know "where am I" during record creation ("File" is enough, but it may be worth to highlight somehow)  
- should be able to change db

All seems clear, but few questions: 

- what is more rare create-action (in particular db or in non-default one) ? 
- how to change db for the record ?

**Comment by antelle** [comment]
:+1:  for need to know "where am I" during record creation: 'File' record should be improved somehow to draw user attention, maybe move it next to fields, or make a combo-box, so it would look like a control.

Sure, more rare create-action is non-default one
Changing db is very important, there's a [TODO](https://github.com/antelle/keeweb/wiki/TODO#future) about it in Future ('drag entries across files'), will be added.

**Comment by antelle** [comment]
closing as no further info was provided. no reports grom other users as well.

**Comment by antelle** [comment]
So, finally we have this select for new records:
![new-rec](https://cloud.githubusercontent.com/assets/633557/15806178/61426cf0-2b46-11e6-926c-cda8e5fcce0b.png)
