### ISSUE TITLE
Interface indicates unsaved changes after clicking into DB settings inputs without making changes

### ISSUE THREAD

**Issue by kasoban** [antelle/keeweb#143]
Steps to reproduce:

1. Create a new DB or open an existing one
2. Go to settings, select your DB
3. Click into any input field (except Master Password)
4. Click outside of it, without having done any changes
5. The DB now has the blue indicator for unsaved changes in the bottom left corner

Interestingly, the master password field does not show this effect.

App Information:

KeeWeb v1.0.4 (a6e7afe, 2016-02-25)
Environment: electron v0.35.6
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.0.4 Chrome/45.0.2454.85 Electron/0.35.6 Safari/537.36

**Comment by antelle** [comment]
fixed and deployed to https://beta.keeweb.info
