### ISSUE TITLE
Inconsistent behaviour when pressing Ctrl+S while input is focused

### ISSUE THREAD

**Issue by kasoban** [antelle/keeweb#144]
When making changes to an input field and pressing <kbd>Ctrl</kbd> + <kbd>S</kbd> to save without deselecting the input first has various different effects.

The IMHO most critical variant:
The input fields in the DB settings dialog, for example the DB name field. When entering a new DB name, and pressing <kbd>Ctrl</kbd> + <kbd>S</kbd>, the save will be executed (a previously existing blue marker disappears), but the old name will be used during the save and will reset the input field to the old name. Same with the master password! This could be confusing.

When doing the same to an input field within an entry, for example the username, the save will not be executed and the currently modified state of the input is not reset.

App Information:

> KeeWeb v1.0.4 (a6e7afe, 2016-02-25)
> Environment: electron v0.35.6
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.0.4 > Chrome/45.0.2454.85 Electron/0.35.6 Safari/537.36

**Comment by antelle** [comment]
currently they are saved on blur, will be fixed, thanks

**Comment by antelle** [comment]
fixed and deployed to https://beta.keeweb.info
