### ISSUE TITLE
KeeWeb is missing entries after opening kdbx converted from kdb by KeePassX

### ISSUE THREAD

**Issue by intenter** [antelle/keeweb#146]
Hi. 

I've been using KeePassX 0.4.3 which works with kdb files - KeePass 1.x format.
I like KeeWeb very much but quickly discovered it doesn't open old format databases, so I've decided to migrate to kdbx format. Installed latest KeePassX 2.0.2, imported my old DB and saved as kdbx.

KeePassX works with the new file just fine. But KeeWeb doesn't display any entries in the file, just shows it's empty.

KeePassX is able to see entries in the new files created by KeeWeb and vice versa.

I'm using KeeWeb 1.0.4 installed with brew.

Any ideas? Is it KeePassX doing bad job during conversion or is it KeeWeb issue?
Thank you.

**Comment by antelle** [comment]
Hello!

That's very strange, as the app is capable of loading such databases.
- Does it repeat on new databases you create in such way? If yes, please attach an example of such db, I'll take a look.
- Please try to do export XML from KeeWeb. What's inside?
- Are there any errors in log (Settings/General/Adnanced/Show Devtools)?

**Comment by dubcanada** [comment]
Try using http://keepass.info/download.html Pro edition to do the conversion. It worked for me on my old kdb database.

**Comment by antelle** [comment]
So, I've downloaded the apps and made these steps:
- created a KDB with KeePass v1.31
- imported kdb in KeePassX
- saved as KDBX with File &rarr; SaveAs
- opened in KeeWeb: works as expected

Attached KDB and KDBX, the password is 'demo'. So I still need a reproduction case, or a sample db which cannot be opened.

[Archive.zip](https://github.com/antelle/keeweb/files/157494/Archive.zip)

**Comment by ampedandwired** [comment]
I just went through this process myself: convert kdb from keepassx 0.4.3 to kdbx using keepassx 2.0.2, then import into keeweb. It seemed to work OK for me. This was on a Linux machine.

**Comment by antelle** [comment]
Tested another way: created a KDB file with KeePassX v0.4.3, imported in KeePassX v2.0.2, opened with KeeWeb - works as well.

**Comment by antelle** [comment]
Please feel free to reopen with sample db or error logs attached.

**Comment by intenter** [comment]
Tried to reproduce and realized it was my mistake in the first place due to weird default folder KeePassX was using to save the new file.

Sorry for confusion and thanks everybody for checking.
