### ISSUE TITLE
Cannot add a new line to the notes field on webapp

### ISSUE THREAD

**Issue by brownpearl** [antelle/keeweb#148]
When one is editing the notes field and presses the enter key nothing happens. New line is not added.

Could you please implement this feature or maybe create a shortcut key for it?

Thank you in advance.

App Information:

KeeWeb v1.0.4 (a6e7afe, 2016-02-25)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by antelle** [comment]
Yes, it's <kbd>shift</kbd>+<kbd>enter</kbd> or <kbd>alt</kbd>+<kbd>enter</kbd>

**Comment by brownpearl** [comment]
Thanks.

I had no idea the shortcut already is already implemented.

I have been using keeweb since only 2 weeks ago.

Regards
Am 03.03.2016 7:41 nachm. schrieb "antelle" <notifications@github.com>:

**Comment by antelle** [comment]
It's rather common shortcuts (Enter with something else), e.g. for MS Excel and other editors.

**Comment by marcioaguiar** [comment]
I think it's often <kbd>ctrl+enter</kbd>. Had to find this issue to find out.

**Comment by antelle** [comment]
In Skype, Excel, Chrome devtools it's alt-enter. I think it depends on apps, and OS.  But we can add ctrl+enter as well for those who prefer this shortcut.

**Comment by brownpearl** [comment]
It is shift+enter that works for me.
Alt+enter or Ctrl+enter do not work.
Cheers
Am 11.03.2016 7:00 nachm. schrieb "Marcio Aguiar" <notifications@github.com
