### ISSUE TITLE
Download and use website favicon bug

### ISSUE THREAD

**Issue by negletios** [antelle/keeweb#150]
The action _''download and use website favicon''_ is failing.I tested it on my own database and on the demo. I opened DevTools and I noticed that there is a weird url manipulation before the request. My entry's url was in that case "https://workable.com".

**DevTools Console Output:**

`GET http://https//workable.com/favicon.ico net::ERR_NAME_NOT_RESOLVED
index.html:13 2016-03-05T18:02:06.054Z [icon-select-view] Favicon download error: http://https://workable.com/favicon.ico Event {}`

I found the bug on v1.0.4  on desktop app for linux, OS: Debian Stretch.

I think it needs more checks about the download url and where the favicon might be located. Lastly, a UX feature might be to inform the user that the KeeWeb couldn't download website's icon, since in my case I restarted the app in order to see if it was a cache thing.

PS: Great app and great work. Thanks for sharing it.

**Comment by antelle** [comment]
Thanks, it's working for webapp and broken for desktop, will be fixed soon.
I agree, we should replace the icon with error sign in case of errors.

**Comment by negletios** [comment]
I would like to add that it is also failing for me in the Web App

**Comment by antelle** [comment]
Hm, that's strange. I've uploaded a new build to https://beta.keeweb.info - does it fail for you as well?

**Comment by negletios** [comment]
Nope, it works for me in this one.

**Comment by negletios** [comment]
FYI: I ran the app (desktop mode, OS: Debian Stretch) in the _develop_ branch and the problem is fixed. The logging is working and in case of failure it displays a forbidden icon.

:+1:

**Comment by negletios** [comment]
There are still some misleading results. If you try to put dropbox.com there is not a possible combination that it resolves to the actual favicon. I believe the problem here is your service (https://favicon-antelle.rhcloud.com) and that it only tries to locate the favicon at the root folder? (I guess, I don't know) 

I think its good a idea to use Google's service about favicons, https://www.google.com/s2/favicons?domain=[query]. It does some pretty good url handling and it tries to get favicons with different ways.The only problem is that is doesn't return 404 on domains with no favicons, it returns a grey _www_ icon.

**Comment by antelle** [comment]
Desktop app downloads the favicon itself, webapp is using the service because of CORS restrictions. Google's service doesn't add CORS headres and cannot be used. We have to download the page first, then search for favicon tag and download it...

**Comment by negletios** [comment]
I think it's a good idea to extend this feature so it works in all case scenarios. Since the whole app is flat, design wised, having colorful small icons gives a more personalized experience.I can help you with the implementation if you want to :)

Either way is a low importance feature so maybe make it full functional on a later version.

**Comment by antelle** [comment]
Hm, you mean grayscale icons?
This is made intentionally and switched in app settings (show colorful custom icons).

**Comment by negletios** [comment]
About the experience I mean about the icons that you mention. About the implementation I am talking about the favicon service.
