### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by gsportelli** [antelle/keeweb#153]
Hi, thanks for your work! No issues so far for me, but I think that a home screen would improve the app usability. The home screen would have only the search bar and maybe the sidebar too. An option to go back to the home screen after a certain amount of time would be also useful for cleaning out any previously opened account.

**Comment by antelle** [comment]
Hello,
Could you please explain in more details, what do you mean? I use a bit different terminology for app parts, so I'm not sure whether I understand you right.
1. homescreen - you mean this:
![keeweb 2016-03-08 12-31-49](https://cloud.githubusercontent.com/assets/633557/13597452/c4380544-e529-11e5-9e17-4e4220f780e9.png)
or this:
![keeweb 2016-03-08 12-32-21](https://cloud.githubusercontent.com/assets/633557/13597457/d3049b78-e529-11e5-862d-ab71dbb514aa.png)
?
2. search bar - what is it?
3. account - ???
4. go back after amount of time - where to go? how? do you mean locking after amount of time? we already have this option.

**Comment by gsportelli** [comment]
Hi,
thanks for your quick reply. We certainly need to define some common terminology :)

1) with home screen I mean something that is visually very similar to the first screenshot, but that serves as the second screenshot. After the user unlocks the database, he could see the same big input text that now serves to search for a record.
2) With "search bar" I mean the text box at the top-center of your second screenshot with the magnifier in it.
3) With account I mean a record of the database. Since this app stores records made of username/password plus some notes, any record wold normally correspond to a user account somewhere.
4) With "go back" I mean a mechanism similar to the one you implemented for locking the database. The difference is that after a certain amount of time you are brought back to the "search bar".

The basic principle is that an user might want to keep the database unlocked during a work day, but he doesn't want his records to be visible on the screen all the time.

**Comment by antelle** [comment]
So, let me paraphrase to check if I got it correctly:
1. from the home screen (which is on my pic.1), you select the db and open it
2. then everything you see is a search box and menu, with no option to see entries list
3. when you search, list appears
4. then you select an entry and go to entry details screen
5. entry details screen will auto-close to screen from (2.)

Is it what you mean?

**Comment by gsportelli** [comment]
Exactly!
Entry details screen might close by pressing something like Esc or automatically, just as with locking.
This is somewhat how it works with operating systems: you can have a timeout after which the pc locks out, or another just for the screen saver.

**Comment by antelle** [comment]
This will break almost all app design concepts and the implementation will be almost equal to creating another app. One of the mockups I made at start was looking something like this, and I had a lot of concerns about such design, so it will not be implemented.
