### ISSUE TITLE
Question for hosted version: disable & hide Dropbox options

### ISSUE THREAD

**Issue by JamborJan** [antelle/keeweb#157]
Hi,

I took the time to package your app for [sandstorm.io](https://sandstorm.io) and I hope you are okay with that. I hope that many more users will be able to use your app that way.

I would like to disable the DropBox feature completely for the Sandstorm version of the app. Is this possible? The user should not see any of the buttons and options related to Dropbox.

If possible I will contribute to your app with alternatives like ownCloud in the future but for now I would need to disable and hide Dropbox.

FYI: this is my repository: https://github.com/JamborJan/keeweb-sandstorm let me know if you have any questions.

Thanks a lot!
JJ

**Comment by antelle** [comment]
v1.1 will have configurable storage providers which will allow to hide Dropbox, GDrive, WebDAV and other icons from the app homescreen, if you need this. To disable it by default in a specific distribution, you will have to add a settings file with predefined Dropbox setting disable option.

**Comment by JamborJan** [comment]
What or where is this settings file in the source code? Or is this something which is introduced in v1.1?

**Comment by antelle** [comment]
I just realized you have to configure web version, not desktop one (where the settings are stored in a json file).
Web version saves settings to localStorage. I'm thinking how to resolve this.
Is it possible, to change a file in the source code while you are buliding the app?
The settings are here: https://github.com/antelle/keeweb/blob/master/app/scripts/models/app-settings-model.js#L7

**Comment by JamborJan** [comment]
Yes I can change settings during build (I do this at the moment to prevent https warning here: https://github.com/JamborJan/keeweb-sandstorm/blob/master/.sandstorm/build.sh#L31).

What do I need to change / add in the settings? Is there also a official options to disable the https warning? I run the app in a secured container with an nginx reverse proxy. So it is definitely not required.

**Comment by antelle** [comment]
I'll add a key for Dropbox and others once storage providers configuration is ready. For now I don't know how it will look like: maybe a separate object, or just key per provider. I'll add a comment in this issue, how to disable it. Https warning is disabled only in localStorage as well, I've just added an option to settings: https://github.com/antelle/keeweb/blob/develop/app/scripts/models/app-settings-model.js#L26

**Comment by antelle** [comment]
I've added the setting: https://github.com/antelle/keeweb/blob/develop/app/scripts/models/app-settings-model.js#L28
Changing the default to `true` will set checkbox to disabled state, and storage provider will be completely disabled. The user will still be able to enable it from settings page, if he wants.
