### ISSUE TITLE
Question for hosted version: save file on server

### ISSUE THREAD

**Issue by JamborJan** [antelle/keeweb#158]
Hi,

I took the time to package your app for [sandstorm.io](https://sandstorm.io) and I hope you are okay with that. I hope that many more users will be able to use your app that way.

As Sandstorm handles the instance of the app like a tiny secured container I would like to store the password protected keepass file and if the user choses to use a keyfile this one too on the server.

Is this possible? Where are the files stored in the file system?

FYI: this is my repository: https://github.com/JamborJan/keeweb-sandstorm let me know if you have any questions.

Thanks a lot!
JJ

**Comment by antelle** [comment]
:+1:  saving file on server will be implemented in v1.1 with WebDAV protocol. I think this will be suitable, no? I have no experience with sandstorm, so I don't know.

**Comment by JamborJan** [comment]
This will be suitable in many aspects. There is no limitation on sandstorm as the instance is a small container and I can decide what it does.

Do you have already a time line for v1.1?

Awesome work! Thanks a lot.

JJ

**Comment by antelle** [comment]
Good, so I'm closing this as WebDAV issue already exists here.
Most of features for v1.1 are already complete, I'm working on storage providers now. I hope the release will happen in Apr..May.

**Comment by JamborJan** [comment]
I guess you are talking about this issue: https://github.com/antelle/keeweb/issues/14?

Sure we can close this one if there is an open one, but we should add a link to the open issue :-)

**Comment by sorin-postelnicu** [comment]
Please note that the link to the WebDAV issue has changed: https://github.com/keeweb/keeweb/issues/14
