### ISSUE TITLE
Question: logo for app store

### ISSUE THREAD

**Issue by JamborJan** [antelle/keeweb#159]
Hey @antelle, would you mind providing me either the SVG or with 4 different sized PNGs for the app store version of your app I'm building for Sandstorm?

The sizes are:
```
        #appGrid = (svg = embed "path/to/appgrid-128x128.svg"),
        #grain = (svg = embed "path/to/grain-24x24.svg"),
        #market = (svg = embed "path/to/market-150x150.svg"),
        #marketBig = (svg = embed "path/to/market-big-300x300.svg"),
```

FYI: this is the app store I'm talking about: https://apps.sandstorm.io. Please note that your project will be linked and all credits go to you - not me. I'm doing this because your app is one of the most useful things I have seen in a while and I want to help making it available to more people.

**Comment by antelle** [comment]
I don't have SVG versions (it's not so hard to make one though).
PNG logos (they are png-24 but if you need a smaller size, you can save to png-8, they will still look pretty):
[logos.zip](https://github.com/antelle/keeweb/files/169954/logos.zip)
