### ISSUE TITLE
No indication for missing database file

### ISSUE THREAD

**Issue by kasoban** [antelle/keeweb#162]
When a database file that was (last) opened with KeeWeb is deleted or renamed, there will be no indication when starting KeeWeb that the file is missing. Instead, it will still ask for the password to unlock it, and will only turn the password field red, suggesting that a wrong password was entered.

Observed with KeeWeb desktop app:
> KeeWeb v1.0.4 (a6e7afe, 2016-02-25)
> Environment: electron v0.35.6
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.0.4 Chrome/45.0.2454.85 Electron/0.35.6 Safari/537.36

**Comment by antelle** [comment]
From now, alert will be shown for all errors which are not invalid key errors, it will contain short error description
