### ISSUE TITLE
Use a longer HSTS max-age for keeweb.info

### ISSUE THREAD

**Issue by ismail** [antelle/keeweb#166]
Currently, HSTS max-age for keeweb.info is 2592000 seconds but the minimum should be 10886400 seconds (18 weeks) to be able to be in the HSTS-preload list (https://www.chromium.org/hsts). Please consider increasing this value.

**Comment by antelle** [comment]
:+1: 
Changed to recommended 6 months.
But there's another condition for adding to list: Redirect all HTTP traffic to HTTPS - I'm thinking how to fix it.

**Comment by antelle** [comment]
Submitted for review to https://hstspreload.appspot.com/
https://www.ssllabs.com/ssltest/analyze.html?d=keeweb.info
![ssl server test keeweb info powered by qualys ssl labs 2016-03-19 16-55-14](https://cloud.githubusercontent.com/assets/633557/13898970/9c8da7b0-edf3-11e5-8e8a-d24461662842.png)

**Comment by antelle** [comment]
Added HTTP redirect to HTTPS for all traffic as well. So the request will be accepted, I hope.

**Comment by ismail** [comment]
Thanks!
