### ISSUE TITLE
Git support

### ISSUE THREAD

**Issue by yusf** [antelle/keeweb#167]
Another interesting way to synchronize would be to have built-in git support. In my view this opens up to interesting ways of distributing databases.

**Comment by antelle** [comment]
No...
1. it's too geeky and unusual even for geeks
2. there's no benefit of storing encrypted file in vcs: there will be no diffs, only backups
3. one can always do this in better ways:
 - setup filesystem backups
 - (or, if we still want to use git) auto-commit changes to git on file change, e.g. using [gitwatch](https://github.com/nevik/gitwatch)
4. we don't want users to flood github with a useless repo with their kdbx files

**Comment by yusf** [comment]
Excellent answers, thank you!

**Comment by kasoban** [comment]
@yusf If you're interested in secure password versioning outside of a KeePass context you might want to have a loot at https://www.passwordstore.org/

**Comment by yusf** [comment]
@kasoban Thank you for the recommendation, but sadly I'm a GUI junkie.
