### ISSUE TITLE
Copy Password without show it in cleartext

### ISSUE THREAD

**Issue by xoxys** [antelle/keeweb#168]
Hi,
is it possible to copy a Password from the App without showing the cleartext password? In KeePass 2 a double click on a password field copy the password to clipboard but dont display the password in clear text.

In a public room it is not the best idea to diplay clear text password before i can copy the entry.

Thanks for your work

**Comment by antelle** [comment]
There are 2 ways:
1. hit Cmd/Ctrl+C
2. click field title (Password)
