### ISSUE TITLE
Feature request - Dekstop entry for linux

### ISSUE THREAD

**Issue by piotrkubisa** [antelle/keeweb#169]
#### Problem

Without Desktop Entry user cannot _pin_ application to dock (i.e. "Keep in dock" in Plank) and also the icon size is incorrectly scaled or there is not application at all.  The problem occurs on any electron based application on Linux with almost all dock software (plank, dash-to-dock for GNOME Shell etc.).

#### Solution

I would love to if KeeWeb would be bundled with a `.desktop` file (e.g.):

```
[Desktop Entry]
Name=KeeWeb
Comment=Kee Web
Exec=/<% path_to_keeweb &>/KeeWeb
Icon=/<% path_to_keeweb &>/resources/app/icon.png
Type=Application
Categories=GTK;GNOME;Utility;
Terminal=false
```

Which will be able to quickly copy into `/usr/share/applications/` (`sudo ln -s "$PATH_TO_KEEWEB/KeeWeb.desktop" /usr/share/applications` if using Bash).

**Comment by antelle** [comment]
Hello!
Which distro are you using? Will this work in all Linux versions?
I need some help in this. Is creating a file with the content you posted enough? What would be the best location for this file? Inside an app folder?

**Comment by piotrkubisa** [comment]
> Which distro are you using? Will this work in all Linux versions?

Yes, (almost) all Linux desktop environments are affected by [.dekstop entry](https://specifications.freedesktop.org/desktop-entry-spec/latest/). I can confirm that problem occurs in Ubuntu and its derivatives. Please note that it is connected to DE not the distro itself. It means any distro with KDE/GNOME (or GNOME-based - i.e. Phanteon, XFCE) uses `.desktop` which works similar to good old `desktop.ini` on Windows.

> What would be the best location for this file?
> Inside an app folder?
> Is anything else required, e.g. creating a script to copy this to desktop?

There are two locations which should be considered:

* `$HOME/.local/applications` - user-specific
* `/usr/local/share/applications` - global configuration

The `KeeWeb.desktop` can be bundled as a template by default and copied into `applications` directory (like Atom [does it](https://github.com/atom/atom/blob/master/resources/linux/atom.desktop.in)). As far as I know there are also a way to improve the [shortcuts in the launcher[(http://electron.atom.io/docs/v0.33.0/tutorial/desktop-environment-integration/)

> Is creating a file with the content you posted enough?

It works for me if I set correct paths, but I am concern that we should modify it slightly to improve search experience (i.e. if you type `password` then KeeWeb will appear in resuts) and consistency to be more meaningful. 

PS. I feel bad because I forgot to thank you in previous post for such awesome application as KeeWeb is! You are great! :+1:

**Comment by antelle** [comment]
Thanks for explanation, I'll add .desktop entry.

**Comment by antelle** [comment]
Now we have .desktop entry in deb package. So once #141 is resolved, I think we can close this. Am I right, or it's better to add .desktop entry to the app archive?

**Comment by piotrkubisa** [comment]
Yes, I think we can close this issue. After creating a installable `.deb` archive I claim it is done (since I prefer debian-based distros). I think that sample desktop entry should be put in the wiki of the instead of the repository.
