### ISSUE TITLE
Keep entries displayed in groups and sub-groups

### ISSUE THREAD

**Issue by Decicus** [antelle/keeweb#17]
In KeePass, my entries are grouped into their respective groups and sub-groups. As shown in the GIF below:
![Example GIF 1 for comparison](https://zippy.gfycat.com/CheerfulDazzlingAsiandamselfly.gif)

However, in Keeweb, they seem to be shown under the main group *and* their sub-groups. Like this:
![Example GIF 2 for comparison](https://fat.gfycat.com/RectangularHastyHomalocephale.gif)

Any way to only have them grouped under their direct sub-groups?

**Comment by antelle** [comment]
In keepass, there's an option to expand subgroups in settings. I'll add such option to app settings as well, enabled by default. For now, there's no way...

**Comment by Decicus** [comment]
Sounds good!

**Comment by antelle** [comment]
I've added an option 'Show entries from from all subgroups' to Settings/General, it will be available in the next v0.2 release.
