### ISSUE TITLE
Where are files and folders located which need to be writable?

### ISSUE THREAD

**Issue by JamborJan** [antelle/keeweb#172]
I'm working on the sandstorm package of your app. The app runs in a sandbox with no write access to any file or folder besides /var. That's why would like to ask if you know which parts of the app need to be write-able. I guess the following are required:
- https://github.com/antelle/keeweb/blob/master/app/scripts/models/app-settings-model.js (or is there a file where this js file saves the settings to?)
- Where does the app save the file when it says "This file is stored in the internal app storage?

Are there any other files or folders which must be writable so that the app is running properly?

Thanks!

**Comment by antelle** [comment]
If the app is launched from browser, it saves everything to localStorage or IndexedDB, you don't have to implement anything.
Settings and the list of last open files are saved [here](https://github.com/antelle/keeweb/blob/master/app/scripts/comp/settings-store.js).
Files are saved in [storage-cache](https://github.com/antelle/keeweb/blob/master/app/scripts/storage/storage-cache.js) for webapp and in [storage-file-cache](https://github.com/antelle/keeweb/blob/master/app/scripts/storage/storage-file-cache.js) for desktop app.

**Comment by JamborJan** [comment]
Thanks for your help. I will have to redirect saving the files to ```/var``` as the app is running in a sandbox type of thing and indexedDb / localStorage is not available. 

Basically the high level process should be:
- user creates new instance of the app
- no password file is there so the user could create a new one or upload one
- when saving the file it is stored to /var (file is still encrypted + password protected and key file is not stored besides it)
- When the user opens the same instance again later, the app opens the existing configuration file **not** from localStorage, but from ```/var```
- Same happens with the password save file
- The app should then directly show the input for the password to open the password file
- Ideally it dosn't show the New and Open buttons any more then, but this an easy to customize thing then I guess

To understand why I want to do it like this you should understand that Sandstorm - the platform I'm packing the app for - is designed to have fine grained app instances. For example when you take a look at the text editors available on the platform: one document is one instance. In the keeweb use-case it would be one password file. On top of this concept the whole user management and sharing is build. So when I finally packed the app it would be possible to share a keeweb instance including password file with my department in case of a use-case in a company our with my spouse when I'm talking about private usage. All available from all browsers and not bound to tools and an OS. The person I share the password file and the app with only needs to know the master password and if required needs the key file.

I'm looking into the files you have mentioned. If you have any further infos and might be willing to help me with the described use-case its of course appreciated.

Thanks!
JJ

**Comment by antelle** [comment]
You might be interested in these files:
- [file-info-collection](https://github.com/antelle/keeweb/blob/develop/app/scripts/collections/file-info-collection.js): this is the list of last open files - if you put an entry to it, the user will see password prompt for this file at startup
- [open-view](https://github.com/antelle/keeweb/blob/develop/app/scripts/views/open-view.js): view for open page with the list of last files
- [open.hbs](https://github.com/antelle/keeweb/blob/develop/app/templates/open.hbs) - open view template, with new and open buttons

Btw, IndexedDB and localStorage are used only in browser, when the app is run in Electron, json and kdbx files are used instead (from Launcher module). So maybe it makes sense, to implement another Launcher, like for Electron platform. I guess you will have to add sort of capability support, e.g. Launcher.supportNodeJs, Launcher.supportOpen, ...

**Comment by koyanoa** [comment]
Hi, I'm using Keeweb on mac, where can I find the place where my keyfile is stored if I selected 'store in the internal app storage'? Thanks

**Comment by antelle** [comment]
@koyanoa if you're using desktop app, please open files from filesystem instead. Save in internal app storage is designed to use on web, or on desktop, as a temporary storage, i.e. when you create a file and don't save it to file.
But if you're interested, it's `~/Library/Application\ Support/KeeWeb/OfflineFiles/`.

**Comment by monsieurhannes** [comment]
@antelle Is that still the case for the latest release? I'm trying to recover one but can't find the folder.

**Comment by antelle** [comment]
@monsieurhannes yes, files are stored in the same location
