### ISSUE TITLE
Ability to open keepass database with just a keyfile

### ISSUE THREAD

**Issue by jmp242** [antelle/keeweb#174]
- what were your actions?
Tried linux version, selected keyfile (I think I selected locally, though it also kept saying "from dropbox"). Tried to open keepass database, got error - password field was highlighted red.
- what was wrong?
KeeWeb assumes you have a password where keepass does not require that.
- app version
1.0.4
- your user-agent (from Settings/Help section)

    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

**Comment by antelle** [comment]
duplicate of #119, fixed on https://beta.keeweb.info
