### ISSUE TITLE
Nested loop with electron while npm install

### ISSUE THREAD

**Issue by floviolleau** [antelle/keeweb#178]
Hi,

Thanks for your great job. it's a very good light app and I love the design/functionalities.

I tried to compile keeweb app under Windows because I do not have an Apple computer :stuck_out_tongue:.

I was stuck during the `npm install` and I spent a lot of time to understand what was wrong.

I found I think one bug during installation/compilation steps on the develop git branch.

During `npm install`, I had those errors:
[error_electron.txt](https://github.com/antelle/keeweb/files/204215/error_electron.txt)

The problem is that npm create nested folders during electron installation and finally, Windows tells to npm STOP... and npm falls into error.

If you replace in the `package.json` the line 50:
`"postinstall": "npm install --prefix electron",`
to this:
`"postinstall": "npm install electron --prefix electron",`

It'll work. I do not know if, if you change that, it'll still be ok for other plateforms.

Kind regards,

**Comment by antelle** [comment]
I guess, the same may happen on another platforms with clean install as well, depending on node and npm versions. I'll change the script today.
