### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by kavolorn** [antelle/keeweb#18]
Last release looks great! Two little things to polish when you have time:

I see a wrong version number in the About page.

<img width="396" alt="screenshot 2015-11-07 05 50 19" src="https://cloud.githubusercontent.com/assets/2448274/11013378/ccc25960-8513-11e5-8265-4a44f4ac33a7.png">

Also contrast between icon and background on my mac is a bit odd. Can you use less saturated color for icon's background?

**Comment by antelle** [comment]
Wow, this is Electron version on about page, I'll fix it. Thanks for opening it, I've never done this :laughing: 
Hm, I'll try to find a better color. Are you using El Capitan or Yosemite? On previous versions the icon will look really from another world and now many icons are saturated but yes, I agree now that it looks strange. I think, maybe I have to add a border as well? 
<img width="129" alt="dock 2015-11-07 08-37-09" src="https://cloud.githubusercontent.com/assets/633557/11013747/c598c6e4-852a-11e5-895f-b548eee72071.png">

**Comment by antelle** [comment]
What's your opinion about this version?
![icon psd 33 3 layer 1 rgb 8 2015-11-07 08-58-13](https://cloud.githubusercontent.com/assets/633557/11013814/c5ae28d8-852d-11e5-83a0-8a1e7f8f9a9f.png)

**Comment by kavolorn** [comment]
I think border can solve the issue! I've tried also to create something useful:

![untitled-1](https://cloud.githubusercontent.com/assets/2448274/11013906/68ce6096-8529-11e5-8894-df9a66271a5d.png)
![untitled-2](https://cloud.githubusercontent.com/assets/2448274/11013907/68f228f0-8529-11e5-8514-38c72fb1f11b.png)

If you give me vector key symbol I can produce high res icon.

P.S. I'm on Yousemite.

**Comment by antelle** [comment]
I have a vector version of this logo, so I don't need a hires icon. I think I'll use my version - please, note slightly less saturated color on it. Here's it:
![icon2](https://cloud.githubusercontent.com/assets/633557/11013963/b58e03a0-8533-11e5-8a63-8910aa156f22.png)

**Comment by kavolorn** [comment]
Great!

**Comment by antelle** [comment]
So, here's how the icon has changed:
![keeweb git 2015-11-07 11-03-27](https://cloud.githubusercontent.com/assets/633557/11014241/563d97b0-853f-11e5-910c-a55832663866.png)

**Comment by kavolorn** [comment]
That should be good! Though GitHub images are blurry on retina screen..

**Comment by antelle** [comment]
I just use monosnap to auto-shrink retina images.. This will be in the next version v0.2, together with About box fix. Thanks.

**Comment by kavolorn** [comment]
<img width="299" alt="screenshot 2015-11-11 13 27 42" src="https://cloud.githubusercontent.com/assets/2448274/11090135/1bf07406-8878-11e5-9492-1d39aaa06942.png">

Icon looks much better now! Still there is a space for improvement. Not very natural comparing to other apps :)

**Comment by antelle** [comment]
It should have a gradient effect, I'll add it. And border will have more contrast. Will post an update today

**Comment by kavolorn** [comment]
Yep thanks :+1:

**Comment by antelle** [comment]
So, I come up with the following:
<img width="395" alt="dock 2015-11-11 21-09-32" src="https://cloud.githubusercontent.com/assets/633557/11098815/93839990-88b8-11e5-8cba-9d4c9ada9561.png">
And the installer:
<img width="347" alt="keeweb 2015-11-11 21-09-03" src="https://cloud.githubusercontent.com/assets/633557/11098811/8ee7d9f0-88b8-11e5-85d7-d49ad383de7d.png">
What do you think?

**Comment by kavolorn** [comment]
yeah! looks great, I like it!

**Comment by antelle** [comment]
I've rebuilt the last release with this new icon, here's the dmg: https://github.com/antelle/keeweb/releases/download/v0.2.0/KeeWeb.mac.dmg

**Comment by kavolorn** [comment]
I like it! Now it feels right :+1:

**Comment by antelle** [comment]
Thank you for putting attention to it
