### ISSUE TITLE
Database locked after minimizing window

### ISSUE THREAD

**Issue by xoxys** [antelle/keeweb#181]
Hi,
im using the 64bit desktop app (v.1.1.0) with Linux Mint 17.3. After minimizing the window to taskbar the database is locked an i have to type in my password. Is it possible to disable this behavior? The settings are set to auto-lock after 10 minutes.

Thanks for your help and your great work

**Comment by antelle** [comment]
Thanks for reporting! This is a new setting which is enabled by default and can be disabled in app settings for OSes where the app can be minimised. But as minimising bug is still not solved on Linux, the section is hidden. Either the bug will be fixed, or the setting made visible.
