### ISSUE TITLE
New feature "save/restore window position after close" doesn't work

### ISSUE THREAD

**Issue by quingix** [antelle/keeweb#182]
Somehow window's size was saved once. But then I tried change it again and restart the app, everything returned back to default position and size. Or maybe I'm doing something wrong?

KeeWeb v1.1.0 (da0b023, 2016-04-05)
Environment: electron v0.35.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/0.4.4 Chrome/45.0.2454.85 Electron/0.35.1 Safari/537.36

**Comment by antelle** [comment]
That's strange, on mac os x it's working stable. But I confirm, for now on Windows 10 it's broken. Will be fixed in the upcoming hotfix.

**Comment by quingix** [comment]
Оперативно, спасибо
