### ISSUE TITLE
Deleted items do not go to trash?

### ISSUE THREAD

**Issue by ymfa** [antelle/keeweb#185]
I clicked on the settings button of a folder, and then in the Group settings (where you set the name and icon of the folder), I clicked on the dustbin icon at the bottom. I intended to just dissolve the folder, while keeping its entries. However, all the entries in that folder got removed without warning!

Then I wish I could at least recover the deleted entries from the Trash. To my surprise, the Trash was empty. I have simply lost a dozen of my entries with one click. I also tested creating a new entry, and then delete it by clicking the dustbin icon. It did not appear in the Trash either.

I wish the Trash could be used as expected, and it will be great to allow deleting a folder while leaving its entries intact. Thanks.

KeeWeb v1.1.1 (88bfa7e, 2016-04-07)
Environment: web
I was using my personal database, and I am new to KeeWeb.

**Comment by antelle** [comment]
It doesn't repeat for me: entries and folders appear in Trash folder after deletion. Please try to do this on Demo database. Do you get the same results? If you, you may have Trash disabled for your db.

**Comment by ymfa** [comment]
I tried on the Demo database (didn't realize there is one) and it worked fine. I double checked and can confirm that I've enabled Trash in my database. Even if I use a new installation of KeeWeb on a different device (namely a MacBook), the problem persists. However, after I unchecked "Enable trash" and checked it again, the function worked!

**Comment by antelle** [comment]
Thanks for the info! I confirm, the issue exists, the fix will be available in a couple of days.

**Comment by antelle** [comment]
Please update, it's fixed.

**Comment by ymfa** [comment]
Cool, thanks!
