### ISSUE TITLE
Can not find database in Google Drive - Web Version

### ISSUE THREAD

**Issue by gynet** [antelle/keeweb#186]
- what were your actions?
Open web app from https://app.keeweb.info/. 
Try to find db from it.
- what was wrong?
It shows "Nothing found. No filles which could be opened. (Files are searched inside undefined folder ).  
- app version
1.1.1
- your user-agent (from Settings/Help section)
KeeWeb v1.1.1 (88bfa7e, 2016-04-07)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
- does it happen on Demo or New database?
Old database

(index):19 Uncaught TypeError: Cannot read property 'value' of nulle.View.extend.copyKeyPress @ (index):19e.View.extend.copyPassword @ (index):19(anonymous function) @ (index):14i.keydown @ (index):14n.event.dispatch @ (index):3r.handle @ (index):3
(index):14 2016-04-10T00:57:26.271Z [storage-gdrive] Listed 199ms

**Comment by antelle** [comment]
Hello! Please search `*.kdbx` your Google Drive. Does it find your databases?

**Comment by gynet** [comment]
Yes, it found. 
Today I tried again on the web app, it did not get repro and works good now. It seems happen randomly.  
Suggest to close it for now.

**Comment by antelle** [comment]
Ok, closing this.
If it happens again, please go to Network panel in devtools and check responses of google drive. 
Also this happens with new files: files created seconds ago will not be visible.

**Comment by blsz** [comment]
The Request URL limits the Google Drive search to a particular mimeType.  KeeWeb finds only those .kdbx files that were directly uploaded through the Google Drive interface and whose Type is "Binary File".   It does not return .kdbx files whose Type is "Unknown File".

Apparently other clients can change the file type.  In my case, KeeWeb is not able to find .kdbx files previously edited by MacPass and the KeePass GoogleSync plugin.

Loosening this restriction would allow KeeWeb to find .kdbx files whose file type is not set to the expected value.

**Comment by antelle** [comment]
mimeType was already discussed in another issue and removed on beta. it will be included in the next hotfix.

**Comment by kasoban** [comment]
@blsz refer to #192 for current state of mimetype handling discussion.
