### ISSUE TITLE
Textarea text color is always black, even in dark themes.

### ISSUE THREAD

**Issue by MrP** [antelle/keeweb#187]
Steps to reproduce
- Open new or demo db.
- Select Flat blue theme in settings
- Go back to any entry, edit the Notes field, see how it's black text on dark.

Seems to me that it should be the same color as the input text is when editing.

I did read the banned features list, and if this is part of the "don't mess with my colors" banned feature, and not a bug, that's fine, happy to see this closed as "won't fix" and have this issue record it explicitly.  As a warning for the next person that wants to mess with the colors :smile: 

I reproduced it in Chrome windows, Firefox windows, and Chrome android.

![textarea color](https://cloud.githubusercontent.com/assets/31433/14408707/b1edb14e-fef7-11e5-91a9-6552282e8b26.png)

**Comment by antelle** [comment]
This is already fixed in cfcd54a1a3eae351b9a5ac6bdfcbf9f6ec9752d1
I'm waiting for some more bugfixed, to include in one hotfix. Will be released soon.

**Comment by MrP** [comment]
Ah, cool, thanks.  I just checked in the beta app to see if it was still happening.  
Next time (there may be a next time!), I'll check if it's fixed in the release branch as well.

**Comment by antelle** [comment]
Yes, it's better to apply hotfuxes to release branches and new features to develop.
