### ISSUE TITLE
Request: Keeweb desktop releases RSS feed (releases.atom)

### ISSUE THREAD

**Issue by fthiery** [antelle/keeweb#189]
Hi

As the Arch AUR package maintainer, i try to keep it up to date but i would like to be notified of new releases through an RSS feed, like on that github project: https://github.com/dailymotion/hls.js

If you take a look, there is an RSS feed available: https://github.com/dailymotion/hls.js/releases.atom

This would help a lot being notified of new releases. Could you take a look please ?

Cheers

**Comment by antelle** [comment]
Hm, what's wrong with https://github.com/antelle/keeweb/releases.atom ?

**Comment by fthiery** [comment]
Well, 
1) it doesn't show up when trying to add it to e.g. feedly (i don't understand why it works on the other project)
2) the title of each entry should contain the version number (not since 25/02 actually) instead of just a label so that it is much clearer

Anyway, just improving the title by adding the version should work !

**Comment by antelle** [comment]
> it doesn't show up when trying to add it to e.g. feedly 

It's feedly issue. The feed [is valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgithub.com%2Fantelle%2Fkeeweb%2Freleases.atom).

> the title of each entry should contain the version number

Is it ok to replace `Desktop apps` with `Desktop apps vX.X.X`?

**Comment by fthiery** [comment]
I'm not saying the feed is not valid, just that it is not detected when adding it. That's not a problem since it works (i just didn't try to guess the url).

Yes, Desktop apps vX.X.X would be perfect !

**Comment by antelle** [comment]
Next releases will have version in title, ok

**Comment by antelle** [comment]
The feed moved here: https://github.com/keeweb/keeweb/releases.atom
