### ISSUE TITLE
[Feature request] Using Dropbox in self hosted app

### ISSUE THREAD

**Issue by AntoineCa** [antelle/keeweb#19]
Would it be possible to use Dropbox in a self hosted instance of your app ?

**Comment by antelle** [comment]
Dropbox limits URLs which your app can use by security reasons.
In a self-hosted app, you will have to create your Dropbox app as well and change Dropbox AppKey in the source code. The only thing which could be done here, is creating Dropbox AppKey setting somewhere deep in advanced settings (to avoid changing source) and an explanation page with instructions, how to create your own Dropbox app.
There's no other way to make it work.

**Comment by s-kostyuk** [comment]
If somebody want to change this key manually: see [here] (https://github.com/antelle/keeweb/blob/master/app/scripts/comp/dropbox-link.js#L7). Or use sed:
`sed -i.bak s/qp7ctun6qt5n9d6/your_won_key/g index.html`
...which especially useful for making changes in index.html of gh-pages branch; will create a backup .bak file before modification.

**Comment by AntoineCa** [comment]
@s-kostyuk it works perfectly, thanks a lot :)

**Comment by antelle** [comment]
I've added description to README, @s-kostyuk, thanks a lot for a tip to use sed.

**Comment by s-kostyuk** [comment]
@AntoineCa @antelle you are welcome

**Comment by antelle** [comment]
Please note: replacing with `sed` will break the app logic in v1.1.
It will be possible to change app folder and key in app settings.
