### ISSUE TITLE
Does the self hosted/beta version support Google Drive?

### ISSUE THREAD

**Issue by 3ruce** [antelle/keeweb#192]
I'm using the latest self hosted index.html file from here https://github.com/antelle/keeweb/tree/gh-pages and have tried the same at https://beta.keeweb.info/

While it appears I can authenticate for Google Drive, keeweb doesn't present a kdbx file to open/view etc. Does anyone know what I'm missing?

**Comment by antelle** [comment]
Self-hosted version doesn't support google drive for now. You can replace clientid with your clientid [here](https://github.com/antelle/keeweb/blob/master/app/scripts/storage/storage-gdrive.js#L5) though.

**Comment by 3ruce** [comment]
ok - interesting - I changed my client ID in the index.html file and authentication worked but Chrome then showed the following errors...

```
(index):14 GET https://www.googleapis.com/drive/v3/files?fields=files&q=fileExtension%3D%2…0and%20mimeType%3D%22application%2Foctet-stream%22%20and%20trashed%3Dfalse 403 ()b.extend._xhr @ (index):14(anonymous function) @ (index):18h @ (index):14
(index):14 2016-04-12T12:05:28.208Z [storage-gdrive] List error 111ms http status 403c.error @ (index):14b._xhr.error @ (index):18(anonymous function) @ (index):14
```
Any ideas on when this might arrive?

**Comment by antelle** [comment]
most probably something with your app url

**Comment by 3ruce** [comment]
hmmm - I read that message to be that google drive/keeweb can't find a kdbx file, even though there is one in the root of my Google Drive folder but I may well be wrong!

I thought some of the stuff here https://github.com/antelle/keeweb/issues/179 might be tangentially relevant?

**Comment by antelle** [comment]
It may also be 403: App with id {appId} cannot be used within the authenticated user's domain

**Comment by 3ruce** [comment]
Maybe - I just entered the web address of where I self host as per the screenshot under Credentials in the API Manager for Google

![screenshot_2016-04-12_14-30-09](https://cloud.githubusercontent.com/assets/1258786/14459932/29458996-00bb-11e6-910a-ba72b0cdfb6e.png)

**Comment by antelle** [comment]
You must add your domain to Authorized origins

**Comment by 3ruce** [comment]
Yeah, it's in - I just didn't include it in the screenshot...

**Comment by antelle** [comment]
So, you have added both origin and redurect uri,  right? Is there anything interesting in the response body?

**Comment by 3ruce** [comment]
This was the response from Chrome

https://github.com/antelle/keeweb/issues/192#issuecomment-208872858

**Comment by antelle** [comment]
403 is response *status*, I mean response body. Like this:
![keeweb 2016-04-12 21-26-54](https://cloud.githubusercontent.com/assets/633557/14471068/61862d12-00f5-11e6-8cc7-e77f21f6831f.png)

**Comment by 3ruce** [comment]
This is what I get in FF

![screenshot_2016-04-12_20-57-56](https://cloud.githubusercontent.com/assets/1258786/14472064/b8fa4ab4-00f1-11e6-97ac-069467a119c8.png)

Access Not Configured. Drive API has not been used in project 385066709169 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive/overview?project=385066709169 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

It may be that I am using the wrong index.html file (possible as I've been testing webdav, dropbox and gdrive) or I've not configured things correctly at Google's end?

**Comment by 3ruce** [comment]
hmmm, I followed that link and activated the Drive API but then got 'nothing found'

![screenshot_2016-04-12_21-09-53](https://cloud.githubusercontent.com/assets/1258786/14472321/f5f66906-00f2-11e6-8041-e5a88370611d.png)

**Comment by antelle** [comment]
Do you have any .kdbx files in your google drive? Try to search *.kdbx here: https://developers.google.com/apis-explorer/#search/drive/drive/v3/drive.files.list

**Comment by 3ruce** [comment]
Yeah, here's the *.kdbx file listed in the results...

![screenshot_2016-04-13_08-23-55](https://cloud.githubusercontent.com/assets/1258786/14484483/2455dd14-0151-11e6-9bd9-467ae7c4380d.png)

**Comment by antelle** [comment]
please check the response of files/list request from the app

**Comment by 3ruce** [comment]
What do you mean/how do I do that? I'm using the self-hosted version if that helps?

**Comment by antelle** [comment]
Open the app, go to devtools, find the second request go google drive which starts with `files`, click it, go to Response tab, check what's returned, are your files there?
> I'm using the self-hosted version if that helps?

Sure, I know it, as we are discussing exactly this case. It's not supported for now, so it's tricky to setup. Later a manual with screenshots will be added, how to set it up. Now it's not tested, so bugs may be there.

**Comment by 3ruce** [comment]
If I've followed your instructions correctly, it looks like a blank response...

![screenshot_2016-04-13_09-55-55](https://cloud.githubusercontent.com/assets/1258786/14486575/f833a6d2-015d-11e6-8ee8-7dca2757a43f.png)

Here's the url I copied from Dev Tools

https://www.googleapis.com/drive/v3/files?fields=files&q=fileExtension%3D%22kdbx%22%20and%20mimeType%3D%22application%2Foctet-stream%22%20and%20trashed%3Dfalse

**Comment by antelle** [comment]
That's because `mimeType="application/octet-stream"`, I guess. It must be removed.

**Comment by 3ruce** [comment]
ok - let me know if you need me to do anything else. I'm assuming this is a bug report/problem that needs fixing in the code?

**Comment by kasoban** [comment]
Google Drive mime type recognition seems to be a little broken sometimes. Sometimes when I upload a .kdbx storage manually it will show "Binary File" in the web view, sometimes "Type Unknown" or whatever.
@3ruce did you happen to upload that .kdbx file yourself, if yes: With which browser, and what does the Google Drive webinterface show under "Type" when you select the file?

**Comment by antelle** [comment]
> I'm assuming this is a bug report/problem that needs fixing in the code?

yes, I'll add this to beta tonight and let you know.

**Comment by 3ruce** [comment]
@antelle - thank you

@kasoban - yeah, I uploaded it with either FF or Pale Moon, I can't recall but I can easily delete and re-upload if you think that will help? Type is currently shown as 'Unknown File' in the GDrive interface, do you think that makes a difference?

**Comment by kasoban** [comment]
Yes, the last time I had the "Unknown Type" situation it refused to work too. It's like antelle said, KeeWeb can't find the file in that case due to the file type filter when querying. Try reuploading with a different browser and see if GDrive recognizes the file as binary, then it should show up in KeeWeb too.

**Comment by antelle** [comment]
It's checking file type and media type. But as long as google drive's media types are so crazy, I'll remove media type checking, so only file extension check will be performed.

**Comment by 3ruce** [comment]
hmmm, I haven't had any joy with FF, Pale Moon or Chromium so far, each time the kdbx file is seen as 'Unnown' do you guys have any recommendations for a browser that works? I might also try on Windows to see if that makes a difference...

**Comment by 3ruce** [comment]
Uploading the kdbx file with FF in Windows works - GDrive sees it as a binary file and then KeeWeb can open it - thanks guys!

**Comment by antelle** [comment]
Fixed mimetype and deployed to beta. Now all mimetypes will be displayed (please note the difference: mimetypes are not extensions, currently we support only .kdbx).

**Comment by 3ruce** [comment]
Thank you @antelle - wouldn't you just believe it though - as soon as I get this working on the host, my wife tells me she can't remember her gmail password!!!

**Comment by antelle** [comment]
Upcoming hotfix (v1.1.3) will contain a method for setting all app settings, including google drive client id:
```javascript
kwSettings.set('gdriveClientId', 'your-key-here')
```
So, you won't need to replace anything in the HTML file.

**Comment by antelle** [comment]
So, all questions seems to be solved except of changing client ID, which is the subject of issue #180
Closing this as duplicate
