### ISSUE TITLE
OSx el capitan not opening

### ISSUE THREAD

**Issue by jaimehrubiks** [antelle/keeweb#193]
I replaced old version with latest 1.1.2 and It won't open, it says it can open application (in spanish)

I just download, open .dmg and drag to applications folder

It doesn't work with version 1.1.1 either.

10.11.3

**Comment by antelle** [comment]
How exactly does it say it? Please try to right-click it and select Open from the menu.

**Comment by jaimehrubiks** [comment]
Ok, I restarted my pc and it started working again, i also deleted cached from Library directory, but i guess reboot was what fixed in my case, sorry and nice app again :)
