### ISSUE TITLE
Copy/paste in Mac OS app

### ISSUE THREAD

**Issue by arogozhnikov** [antelle/keeweb#2]
Hi, thanks for your project!

In Mac Os app copy/paste/select all hotkeys seem to be broken, but "Generate" works, and those named in 'help' work too.

Web-version hosted on your site works fine.

* Mac os 10.9
* Browser: chromium

**Comment by antelle** [comment]
Thanks for reporting! I found it out, that's because the menu is removed. Also cmd-H doesnt work. I'll add these menus back.
