### ISSUE TITLE
Files saved in KeeWeb cannot be opened in KeePass2

### ISSUE THREAD

**Issue by ShaunMaher** [antelle/keeweb#203]
Hi.

When I open an existing file, add an entry and save the file, users of KeePass 2 are unable to open the file.  They receive the following error:
![image001](https://cloud.githubusercontent.com/assets/6510825/14662312/44dfdc22-06f8-11e6-921e-1bb29ec2ff72.png)

This issue sounds very similar to #127 which is closed.  Maybe the fix has not rolled out to the non-beta app yet.  I'm using KeeWeb v1.1.2 (the electron client) on Ubuntu 14.04 (amd64).

Thanks again for your time.

Shaun.

**Comment by antelle** [comment]
#127 is about custom build errors, it's totally different.
- what were your actions?
- does it happen on Demo or New database?
- if you are using a test db without your personal data, please attach it

**Comment by antelle** [comment]
I figured it out.
This happens when any of field, or title, or something else contains `]]>`. Looks like XML encoder doesn't handle it correctly.

**Comment by ShaunMaher** [comment]
Hi @antelle.  Do you still need an example or do you have a good enough test case?

**Comment by antelle** [comment]
No, I don't need an example, the case is clear to me and repeatable. The fix will be made today or tomorrow.

**Comment by ShaunMaher** [comment]
Your responsiveness is truly amazing.  Thanks so much!

**Comment by antelle** [comment]
https://github.com/jindw/xmldom/issues/164

**Comment by antelle** [comment]
Fixed, uploaded the release, please update the app, now it should work as expected.
