### ISSUE TITLE
Self Hosting with Dropbox

### ISSUE THREAD

**Issue by marifrahman** [antelle/keeweb#207]
Hi,
I am trying to self host KeeWeb 1.1.3. 
1. Got it downloaded from  https://github.com/antelle/keeweb/tree/gh-pages
2. Within the index.html file changed the dropbox app key with the one from my dropbox app.
3. hosted the index.html file in the public folder on dropbox - so that I can access it with url. [Not sure if this right/wrong !!]
4. When I access the url to index file - I see the settings is open where my app key is showing up.
5. Now when I connect to dropbox it asks for permission for the app access and when I allow I can create and  save keys in dropbox.
6. But when I access the url from some other browser its the same process again.

I was thinking if I change the dropbox app key - and once permission provided for the url - dropbox will become the datastore - that whenever I access the index file will automatically get connected.

I might be misinterpreting the whole thing - can anybody please share a 'complete' self-hosting guide with dropbox ?

**Comment by antelle** [comment]
Hello!
3. - currently this is untested path, it's better to host on your web server. So, I see it finally works for you, right?
6. - but once connected, next time you open this browser, you can open/save files as usual, right? from which point 'the same process' repeats?

**Comment by marifrahman** [comment]
Hi,

​Thanks a lot for replying.​

​For same browser it keeps working. But whenever I try to access the url -
its again the same process to authenticate the url with dropbox app.

​As you are saying I should try with web server ​
​
​- I will definitely try with ​one of my Apache server and will update.



​

**Comment by antelle** [comment]
That's expected: auth details are stored inside browser storage and of course they are absent for other browser.
