### ISSUE TITLE
Private keys storage

### ISSUE THREAD

**Issue by renatn** [antelle/keeweb#208]
Привет!

Не знаю если эта возможность  в оригинальном КeePass'e. Но хотелось бы иметь возможность хранить файлы ключей в хранилище.

**Comment by kasoban** [comment]
You can add a file to an entry by dragging and dropping it to the paperclip icon in the bottom right of a entry. The text is hidden unless you hover your cursor over it.
Here:
![keeweb-attachment](https://cloud.githubusercontent.com/assets/567466/14740294/1f2f0362-088e-11e6-9ae5-462b6b3c4f54.png)

**Comment by antelle** [comment]
looks like everything is already here...
