### ISSUE TITLE
Не синхронизируются файлы открытые по WebDav на разных устройствах

### ISSUE THREAD

**Issue by renatn** [antelle/keeweb#211]
Привет!

1. Открыл в браузере на десктопе файл по WebDav
2. Открыл в браузере на айфоне тот же файл по WebDav
3. На десктопе внёс изменения, сохранил
4. Переоткрыл файл на айфоне - **изменений нет**.

Так и должно быть? Или я что то не так делаю?

**Comment by antelle** [comment]
Looks like a bug. Please attach logs from dev console. Here's a short manual how to do this in mobile safari: http://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787

**Comment by renatn** [comment]
Сорри, нет мака чтобы запустить Safari. А для Windows его вроде уже давно не выпускают

**Comment by antelle** [comment]
https://beta.keeweb.info
Settings &rarr; Advanced &rarr; Show app logs

**Comment by antelle** [comment]
iPhone, Seafile+Apache &ndash; ok.
