### ISSUE TITLE
Server-side file storage

### ISSUE THREAD

**Issue by tanji** [antelle/keeweb#212]
Hi!

I am self-hosting a keeweb application using Docker. Is it possible to store the kdbx file on the server instead of local file storage? e.g. Let's say I would like to have a /keeweb/data volume in my container and have keeweb read and write to there. That would be a must have for sharing a keepass db.

Thanks!

**Comment by renatn** [comment]
WebDav?

**Comment by kasoban** [comment]
You will have to add some file storage I/O service yourself, right now WebDav is one of the supported ones, as @renatn pointed out.
Since KeeWeb never "runs" on the server but within the client browser, it makes no sense to integrate server-side I/O mechanisms into KeeWeb.
What *would* be an interesting idea though would be the ability to predefine links to kdbx resources from whichever source for the to-be-served client. That way you could open your installation from whereever and be good to go by just entering the password.
@antelle is it possible to inject a keepass db as top element of the "last used database" list at startup from a sideloaded file?

**Comment by antelle** [comment]
@tanji  for this, you can create a container from this and add webdav components to it. Maybe we have to setup webdav by default or as a docker option, or separate container, currently I'm thinking about it...
@kasoban in future, we may have server-side settings storage for standalone installation. E.g. add pre-configured webdav link, save options from settings, remember last open files, ... but this needs some work, special ui option and maybe a special build task for it. May be added in future.

**Comment by tanji** [comment]
@antelle Thanks for the webdav container idea. Sounds good enough.
My initial thought was to implement a nodejs service with websocket and stream binary data from keeweb to the nodejs backend. Do you think this is something that could work? I could try myself at a PR if I have some time.

**Comment by antelle** [comment]
We don't need a backend which would be aware of file contents: WebDAV and other storages are enough.

**Comment by tanji** [comment]
Fair enough.

For the record, I created a webdav container (I don't think it is good practice to modify the keeweb container. Using an existing nginx or apache webdav container will do). However, I get an ERR_INSECURE_RESPONSE in the Javascript console. I guess JS doesn't like the fact that the cert is self-signed, and IIRC there is no workaround.

**Comment by antelle** [comment]
Sure, you have to get a valid cert

**Comment by hellodanielting** [comment]
Slightly off-topic. Getting a valid cert these days is easy.
You can try using [LetsEncrypt](https://letsencrypt.org/getting-started/) to get your free cert.

Hopefully that helps.

**Comment by tanji** [comment]
I am aware of all of this. Testing with self signed certs is easy, that's why I asked.

**Comment by antelle** [comment]
Closing this as the question looks like answered and no action is required. Not sure in container with storage options, since it's rather easy to create.

**Comment by christopher-davies** [comment]
WebDav is insecure and not supported though secure corporate networks. 
Keeweb should be redesigned to run on the server like php otherwise it is very insecure and I wont be advising anyone to use it.

**Comment by antelle** [comment]
WebDAV is neither secure, nor insecure. It depends on the underlying protocol, how you configure it.

**Comment by vavrecan** [comment]
https://github.com/keeweb/keeweb/issues/828
