### ISSUE TITLE
Network error using webdav on Online Web App

### ISSUE THREAD

**Issue by guypi** [antelle/keeweb#213]
Hi,

I'm trying to load my kdbx file from box.com on the Online Web App and getting Network error.
It happens both on Chrome and Firefox (Desktop and Android). On local Linux client it works OK.

KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36  

Console log:
Failed to load resource: the server responded with a status of 401 (Unauthorized)
(index):1 
XMLHttpRequest cannot load https://dav.box.com/dav/Keepass/guyskeepass.kdbx. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://antelle.github.io' is therefore not allowed access. The response had HTTP status code 401.

Thanks.

**Comment by antelle** [comment]
https://github.com/antelle/keeweb/wiki/WebDAV-Config
> Please note: OPTIONS request must work without authorization.

Your server denies OPTIONS requests without authorization. It's not possible to work with this server from web.

**Comment by dodedodo** [comment]
Correct link: 
https://github.com/keeweb/keeweb/wiki/WebDAV-Config

**Comment by Nick0278** [comment]
@antelle I have got the same problem and that's

> Correct link:
> https://github.com/keeweb/keeweb/wiki/WebDAV-Config

probably the solution, but I am new here and do not know how to use it.
This is the vhost (https://github.com/keeweb/keeweb/wiki/WebDAV-Config) i need.

```
RewriteEngine on
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ blank.html [R=200,L,E=HTTP_ORIGIN:%{HTTP:ORIGIN}]

<Directory "/path/to/your/directory">
  AuthType "Basic"
  AuthName "Password Manager"
  AuthBasicProvider file
  AuthUserFile "/your/htpasswd.file"
  Require user someuser

  DAV On
  Options Indexes
  Header always set Access-Control-Allow-Origin "*"
  Header always set Access-Control-Allow-Headers "origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite"
  Header always set Access-Control-Expose-Headers "ETag"
  Header always set Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
  Header always set Access-Control-Allow-Credentials "true"
</Directory>
```

Which part is necessary for my problem?


This is the vhost I am using now (and its not working):

 ```
<VirtualHost *:80>
        Servername webdav.domain.com

       DocumentRoot /var/www/webdav
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/webdav/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
        </Directory>

Alias /data /var/www/webdav/data
<Location /data>
    DAV On
        AuthType Basic
        AuthName "data"
        AuthUserFile /usr/local/apache2/webdav.passwords
        Require valid-user
</Location>

RewriteEngine on
RewriteCond %{SERVER_NAME} =webdav.domain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
        Servername webdav.domain.com

        DocumentRoot /var/www/webdav
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/webdav/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
        </Directory>

Alias /data /var/www/webdav/data
<Location /data>
    DAV On
        AuthType Basic
        AuthName "data"
        AuthUserFile /usr/local/apache2/webdav.passwords
        Require valid-user
</Location>

Include /etc/letsencrypt/options-ssl-apache.conf
Header always set Strict-Transport-Security "max-age=31536000"
SSLCertificateFile /etc/letsencrypt/live/webdav.domain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/webdav.domain.com/privkey.pem
</VirtualHost>
```

What do I need to change in the current configuration to be able to integrate the password file with webdav?

Thanks!

**Comment by antelle** [comment]
@Nick0278 I'm very sorry, but I don't help with server configs. I can say requirements to the server, it's your responsibility to meet them.
