### ISSUE TITLE
I cannot not connect to dropbox after upgrading to v1.1.4

### ISSUE THREAD

**Issue by brownpearl** [antelle/keeweb#215]
Hello,

I am self-hosting the app using the gh-pages. Since I upgraded to v1.1.4 I cannot access the db on my dropbox apps folder anymore.

When I enter my app key and press enter the page reloads and prompts me to "click to open a file".

App version:
KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

Any help is appreciated.

Thank you in advance

**Comment by antelle** [comment]
Hello!
Are you using custom Dropbox key?
In v1.1.4 replacing key in html file doesn't work anymore, you have to set it in app settings.

**Comment by brownpearl** [comment]
Hello,

Thank you for the reply.

I do not understand what you mean with custom dropbox key.

I have been using the key that was generated when the app folder was
created. I has worked very well.

Now I have downloaded a new html file an hour ago and tried without
replacing the key in html but it still not working.

I get the following error message:

"The file was not found. has it been remove from another computer"

Could you please tell me exactly what I have to do to get it working again?

Thank you in advance

**Comment by antelle** [comment]
> what you mean with custom dropbox key

I mean a custom Dropbox app. Previously this key was replaced in html. Are you using predefined app or your app? In other words, what's the name of the app folder in your Dropbox?

**Comment by brownpearl** [comment]
Hello,

I've got it working!

I just needed to leave the app folder field empty. I entered the folder
name in app folder field. It start working the moment I removed it.

Thank you for your help
