### ISSUE TITLE
Search within hidden custom fields

### ISSUE THREAD

**Issue by philogit** [antelle/keeweb#222]
KeeWeb returns search results on all fields, including custom fields, except for ones that are hidden (locked). I'd like KeeWeb to return search results on hidden fields, too.

Common use example: I store credit card numbers in custom fields and I often will search for a credit card number (e.g., when looking up the last four credit card numbers found on on receipts). However, as soon as I hide the field, it's no longer available for searching. 

(I see that this also applies to passwords, which, of course, are always hidden.)

===
KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: electron v0.37.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.1.4 Chrome/49.0.2623.75 Electron/0.37.4 Safari/537.36

**Comment by antelle** [comment]
This is already available in advanced search options
![keeweb 2016-05-13 09-09-29](https://cloud.githubusercontent.com/assets/633557/15239406/fc6d6ad6-18ea-11e6-8dee-dccdb6fe92a9.png)

**Comment by antelle** [comment]
This is already available in advanced search options
![keeweb 2016-05-13 09-09-29](https://cloud.githubusercontent.com/assets/633557/15239406/fc6d6ad6-18ea-11e6-8dee-dccdb6fe92a9.png)

**Comment by philogit** [comment]
Thanks for pointing that out. I was totally unaware that the lens icon did anything more than execute a search.

**Comment by antelle** [comment]
We have to add something to it. Maybe sort of ddrodown-like arrow...

**Comment by philogit** [comment]
Yes. Something like that should cue the user.
