### ISSUE TITLE
Enter key should inset new line in notes field

### ISSUE THREAD

**Issue by philogit** [antelle/keeweb#225]
## Current behavior:

Currently, pressing the 'enter' key in the notes field moves the cursor to the next field. The user must press shift-enter to get a new line.

## Expected behavior: 

Pressing the 'enter' key should insert a new line in the notes field. The tab key can continue it's current behavior of moving the cursor to the next field.

===
KeeWeb v1.1.4 (928b561, 2016-05-13)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by antelle** [comment]
No. To insert a newline, please use alt-enter or shift-enter or ctrl-enter, depending on your OS and habits.

**Comment by philogit** [comment]
>No...

I'm not sure why this enhancement request was dismissed without explanation.

The current behavior violates users' expected behavior in multiline textarea fields. Also, KeePass users expect 'enter' to create a new line.

If this were a spreadsheet-style application, of if the field were a singular 'note', then I could understand why maintaining consistency between fields would be important. But here, users enter are free to enter many lines of notes and should expect 'enter' to work as expected. So, asking users to alter their behavior doesn't serve to improve the user experience.

Please reconsider or make it a configurable option.

**Comment by antelle** [comment]
In future releases, all custom fields will support multi-line editing, not only notes #107
The user don't need to know whether is notes, or other multiline field, or regular field (password, username, ...): Enter key must behave in the same way for all fields.
So, we have two options:
1. make it to insert a newline and perform no operation in single-line fields
2. insert a newline inside multiline fields and do nothing in other fields (as now)

As we don't have Edit/OK buttons, it's expected that Enter and Esc will close editing mode.
Assuming that applying changes is much more frequent case (compared to newline), we'll follow the first way.
