### ISSUE TITLE
SMB shared database file?

### ISSUE THREAD

**Issue by pwFoo** [antelle/keeweb#229]
KeeWeb looks great and works supports Dropbox, GDrive, ... and is smb / cifs also supported? The database file is stored at my NAS.

**Comment by antelle** [comment]
It's available to open as a regular file, from the desktop app.
There's no possibility to open it from web.

**Comment by pwFoo** [comment]
Thanks, I'll test it :)

**Comment by pwFoo** [comment]
Missed the "\\"... Looks like Windows. Is it also possible with (Debian) Linux?

**Comment by antelle** [comment]
You can mount the smb share and open the file from it

**Comment by matthias-kuklinski** [comment]
Is it nowadays possible to write back changes to the database while using the web-client? The web-client shows: "This file is stored in the internal app storage."

I'm self hosting keeweb in a docker container and I would like to read **and write** changes (sync) to the currently opened database. The database resides on a SMB share (mounted with cifs) and is accessible by multiple clients across the network (therefore I would like to sync every write).
