### ISSUE TITLE
Items don't get copied to clipboard by clicking on the label

### ISSUE THREAD

**Issue by matteoipri** [antelle/keeweb#237]
Hi,
I cannot get items copied to the clipboard when I use the web app in Safari.
Steps to reproduce:

0. go to https://app.keeweb.info
0. choose an entry from the password list, for example the fourth, "Facebook"
0. select it
0. click on "User"

"smith" gets highlighted and selected but not copied to the clipboard. The "Copied" HUD doesn't show either.

KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

This works in other browser or in the desktop app.

Thanks for your attention
Matteo

**Comment by antelle** [comment]
Unfortunately, Safari doesn't support HTML5 copy API, so we select the field, to make copying it a bit easier.
