### ISSUE TITLE
⌘C does not copy password on MacOSX 10.11.1 (15B42)

### ISSUE THREAD

**Issue by paul-alkhimov** [antelle/keeweb#26]
I cannot copy the selected password on Mac.
Actually, I cannot copy anything from this application at all.

KeeWeb v0.2.1 (built at 2015-11-10)
Environment: electron v0.34.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/0.1.0 Chrome/45.0.2454.85 Electron/0.34.0 Safari/537.36

**Comment by antelle** [comment]
You are using an old desktop client version (KeeWeb/0.1.0).
Please, [download](https://github.com/antelle/keeweb/releases) the latest release and try on it, it has been fixed (auto-update for now is a mess, but I'm working on it).

**Comment by antelle** [comment]
duplicates #2

**Comment by antelle** [comment]
please, reopen if it repeats
