### ISSUE TITLE
[Feature request] Adding a Cask

### ISSUE THREAD

**Issue by isbad** [antelle/keeweb#27]
It would be nice to have an [ability](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask) to 
```bash
brew cask install keeweb 
```
Thank you !

**Comment by antelle** [comment]
Thanks, I'll add it, once updater and versioning will be ok.

**Comment by Gutem** [comment]
I can be a Mac maintainer and do it, if you want...

**Comment by antelle** [comment]
I'm just waiting for some more stable version... I'll add it once it happens. :neutral_face:

**Comment by antelle** [comment]
Done in https://github.com/caskroom/homebrew-cask/commit/080a1eafdd90591595252693aa70cf7b8f51e47f
