### ISSUE TITLE
How to debug this app

### ISSUE THREAD

**Issue by tinybug** [antelle/keeweb#29]
Hello antelle ! Can you tell me how to debug this app, I'm really new to webpack. THANKS!!!

**Comment by antelle** [comment]
Hello,
To debug the app:
1. build it with `grunt` 
2. start `grunt watch`
3. change any .js
4. changes are wached and debug script in tmp/ is rebuilt
5. open tmp/index.html

**Comment by tinybug** [comment]
Thanks antelle ! But I want to debug scripts step by step and auto reload via webpack. Is it possible to do that ?

**Comment by antelle** [comment]
Personally I never use auto-reload, so if you want, you can add it and create a grunt task which will execute `watch` task and start auto-reload after it. Maybe I'll add this option later.

**Comment by tinybug** [comment]
I have saw *devDependencies  *catains *webpack-dev-server *in package.json,
but I haven't see that been used in any script, just ask for curiosity.
Anyway, thanks a lot.

**Comment by antelle** [comment]
It was used before but then it became tricky to configure, maybe I'll fix dev-server later on.

**Comment by tinybug** [comment]
I appreciate it. I will try it on my own too.

**Comment by antelle** [comment]
I've added info to readme, now it should be more clear. Closing for now

**Comment by tinybug** [comment]
Well done, Thanks!
