### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by kavolorn** [antelle/keeweb#30]
There are two nice improvements to consider:

1. New version notification without automatic update.
2. Automatic memory cleanup after few seconds (very nice feature from KeePass).

**Comment by antelle** [comment]
1. will be added soon,
2. will be resolved with 'secure inputs for all passwords' issue (now only master-password has secure input; when the user starts editing protected fields, inputs are insecure, so memory dump can show field being edited)

**Comment by kavolorn** [comment]
Super! Will be waiting for next release!

**Comment by antelle** [comment]
Option to check updates without install was implemented in 94fd93ab9dfdcc909e36458927b44bde3b2d57c5.

**Comment by kavolorn** [comment]
Great, I'll wait for next release and test it. Thanks!
