### ISSUE TITLE
[Error] Dropbox unaccesible from self-hosted page

### ISSUE THREAD

**Issue by Rurik19** [antelle/keeweb#35]
Dropbox says:
Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.
More details for developers
Invalid redirect_uri: "https://******.ru/keeweb/": It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

**Comment by antelle** [comment]
This is not allowed by Dropbox for security reasons, you have to create your app.
Please, read the [README](https://github.com/antelle/keeweb#self-hosting) or [FAQ](https://github.com/antelle/keeweb/wiki/FAQ#self-hosting), to get an idea, how to make it work.

**Comment by antelle** [comment]
I have an idea: as this happens quite often. I'll add a message about this to the app, and when you click Dropbox icon from self-hosted page, you will get a description what's going wrong.

**Comment by Rurik19** [comment]
thank you!

**Comment by antelle** [comment]
I'll reopen it and fix by adding a warning dialog to the app in the next release.

**Comment by antelle** [comment]
I've implemented it, and the next version will show this alert:
![keeweb 2015-11-16 21-12-33](https://cloud.githubusercontent.com/assets/633557/11190512/ff6abbe2-8ca6-11e5-8ba7-fd1feac62633.png)

**Comment by Rurik19** [comment]
I've made the dropbox application, got the app key, wrote it to index.html, set up redirection url in dropbox settings, but I have the dropbox error anyway (the redirection url IS exactly match as in the error):

Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.


More details for developers

Invalid redirect_uri: "https://******.ru/keeweb/": It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

**Comment by antelle** [comment]
Have you included your redirect url to your app settings?

**Comment by antelle** [comment]
App settings should look like:
![developers - dropbox 2015-11-18 09-34-14](https://cloud.githubusercontent.com/assets/633557/11234314/b51083f6-8dd7-11e5-8cac-b0a582ff2067.png)

**Comment by Rurik19** [comment]
Yes, I wrote the redirection url (exactly as in the error); chooser/saver domain I've just added, but it doesn't help. Does "production status" matter? I have "development" there.

**Comment by Rurik19** [comment]
Yep! Another browser managed to do it! Somethig in the browser cache prevent of right authorising.

**Comment by antelle** [comment]
Unless you're not expecting 100+ users on your server, development status is ok:
https://www.dropbox.com/developers/reference#production-approval

**Comment by antelle** [comment]
> Somethig in the browser cache

Probably you updated the html but haven't changed the manifest. The app will not be reloaded in this case, this is app cache: https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by Rurik19** [comment]
Ok, dropbox authorising works. Next issue: place to put file in dropbox. You message says it is "apps/keeweb"; but the really place in my case is "Приложения/My keeweb" . I.e. folder "apps" depends of language and apps folder is application name.

**Comment by antelle** [comment]
Hm, where's message with 'apps' in the app? I don't remember it :)

**Comment by Rurik19** [comment]
When no kbdx files in dropbox yet and I press dropbox icon on very fist screen

**Comment by antelle** [comment]
Please make a screenshot of it. Is it insode the app or in Dropbox popup? There are no hard-coded Apps string, hm...

**Comment by antelle** [comment]
Oh I see now, there is one. It should be replaced, yes, thank you.

**Comment by Rurik19** [comment]
Voila
![dropbox](https://cloud.githubusercontent.com/assets/1955806/11236096/a9702508-8df8-11e5-802c-7d588bdf82c7.png)

**Comment by antelle** [comment]
:+1:
