### ISSUE TITLE
Wrong css font string

### ISSUE THREAD

**Issue by mokrinsky** [antelle/keeweb#39]
Maybe it's something on my side, but... When I tried to compile keeweb myself, I've got the following in stylesheet:
`font: normal normal normal 14px/\ 1 FontAwesome;`
Which is obviously not working, it breaks all the icons. I tried to investigate this trouble, this line breaks after `postcss` grunt task. I've read a changelog of cssnano which is executed in `postcss` and found that there was a fix of this trouble in 3.0.x. When I upgraded cssnano to the latest version, everything gone fine. So... Maybe it's a bug that there is an old version in your package.json?

**Comment by antelle** [comment]
Thanks for mentioning this,
I have v2.6.1, and it works for me. I think the trouble is somewhere between my version and v3. Installed v3, checked it and it works, thanks.

**Comment by antelle** [comment]
fixed in b276a49cc9bcbde205d4733eda8fd289a3500d91
