### ISSUE TITLE
File can be open as broken, entries have empty File and cannot be deleted

### ISSUE THREAD

**Issue by Taurus01** [antelle/keeweb#40]
!please, describe your issue here!

KeeWeb v0.3.0 (f7fa11a, 2015-11-14)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0

Что сделать можно?
Пока очень нравится ваша работа!

**Comment by antelle** [comment]
Please, describe how you delete them. Simple case is working: open Demo file; hit Delete button inside entry; it appears in Trash.

**Comment by Taurus01** [comment]
Как-то так (как на рисунках - и в браузере и в десктопе):
![dell01](https://cloud.githubusercontent.com/assets/15903777/11235528/068e346e-8ddb-11e5-9851-5f91f1712f03.jpg)
![dell02](https://cloud.githubusercontent.com/assets/15903777/11235530/0690b978-8ddb-11e5-9b7c-28652540f385.jpg)
![dell03](https://cloud.githubusercontent.com/assets/15903777/11235529/068e7d5c-8ddb-11e5-9a70-7690d15749e9.jpg)

В корзине пусто в результате удаления- базу создал в KeeWeb, переместил в Dropbox, вытащил из Dropbox для десктопа - удаляет, но не в корзину.

**Comment by antelle** [comment]
:+1:

**Comment by antelle** [comment]
This is the reason, and I need more info on this, how to open a file in such way:
![b55e2878-8ddb-11e5-86fb-2d3ee513480b](https://cloud.githubusercontent.com/assets/633557/11263496/3cdf3ef2-8e9c-11e5-904f-87b2e1499dc1.png)

If anyone notice similar trouble, please, let me know. I'm still searching...

**Comment by antelle** [comment]
Closing until more info is provided
