### ISSUE TITLE
[Error] Windows client: after update to 0.3.0 there is no Dropbox button 

### ISSUE THREAD

**Issue by Rurik19** [antelle/keeweb#41]
![2015-11-19_150459](https://cloud.githubusercontent.com/assets/1955806/11267746/fe4931f6-8ece-11e5-84e9-fc44a5056fe9.png)

**Comment by antelle** [comment]
It's intentionally removed because Dropbox in desktop was buggy.
This was fixed in develop branch, commit b5aebd791721b59f6f061a9e70bedf2d6b4252bd, and will be released in next upcoming release v0.4

**Comment by Rurik19** [comment]
ok
