### ISSUE TITLE
[Feature Request] Add context menu for tray icon

### ISSUE THREAD

**Issue by Sigmanor** [antelle/keeweb#44]
Please add context menu for tray icon, because when you turn the application in the system tray, it can be closed only through the Task Manager.

**Comment by antelle** [comment]
Thanks! I've forgot that there's no quit command on Windows. I'll add it in a couple of days and publish an update.

**Comment by antelle** [comment]
It's closed. To update, please, download a new version. 
There's a strange bug with auto-updater on Windows... I'm still researching it.

**Comment by Sigmanor** [comment]
@antelle Yes I noticed a bug with auto-update. Already downloaded the new version, thanks!

**Comment by antelle** [comment]
Hope it works for you, if you notice something strange, please reopen this issue. For me, the only problem now is close if you have unsaved changes (shows a question instead of silent locking; will be fixed in v0.5 with merge sync).
