### ISSUE TITLE
Groups and entries arranging

### ISSUE THREAD

**Issue by 4ndv** [antelle/keeweb#5]
Please add ability to arrange groups and entries. And, btw, create new builds of desktop apps :)

**Comment by antelle** [comment]
Of course, ability to move groups and entries will be added soon, it's already planned in TODO.

**Comment by 4ndv** [comment]
Oh, my bad, missed it. But, new builds of desktop app is still required! :)

**Comment by antelle** [comment]
Now a desktop app just loads webapp page and caches it - so it's like an app with mandatory updates. I'm working on flexible update system in `no-auto-update` branch for now, this will happen in 1.0 release. Now apps don't need updating, they just use the latest version.
But why do you think they need updating? Maybe I'm missing something important.

**Comment by 4ndv** [comment]
Troubles with default hotkeys like Super+V, Super+A in fields, and, i think nothing important more. And funny bug: if you create group without name, it will be very hard to select for renaming/deleting.

**Comment by antelle** [comment]
Oh, I see now, you just mean that it contains many bugs. Hotkeys are #2 and will be fixed very soon. I thought it was an update issue. Group without names definitely should not be created, I'll fix that, thanks for mentioning.

**Comment by antelle** [comment]
Added #11 for group without a name
