### ISSUE TITLE
Add an option to minimize to system tray

### ISSUE THREAD

**Issue by ismail** [antelle/keeweb#51]
This would be very useful on desktops.

**Comment by antelle** [comment]
I suppose you're on Linux, right? I'll add support for Linux. Minimize to tray feature was recentry added but only for Windows. 
For Mac, having dynamic menulets is uncommon, according to [Apple HIG](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html):
> Users, and not apps, place menu bar extras in the menu bar..

**Comment by ismail** [comment]
Yes this is on Linux, thanks!

**Comment by piotrkubisa** [comment]
It is connected with the #169. I think that after adding a `KeeWeb.desktop` entry problem may be marked as fixed.

**Comment by antelle** [comment]
According to [Electron Documentation](http://electron.atom.io/docs/v0.37.2/api/tray/), for Linux distributions a user has to install a special package, `libappindicator1`, I'm still thinking how to detect if it's installed and show/use and option depending on it, that's why this feature is harder to add specifically for linux.

**Comment by antelle** [comment]
As long as minimizing is now working on Ubuntu without any additional packages, it will be enabled in the upcoming hotfix.

**Comment by aroumeliotis** [comment]
Hi! I still don't see the option to start minimized! Am I missing something?
I'm on linux mint 18.3 with keeweb 1.6.3
https://snag.gy/1DEx5b.jpg

**Comment by antelle** [comment]
@aroumeliotis it's here:
![minimize](https://user-images.githubusercontent.com/633557/34838165-661d2e02-f6fd-11e7-8e19-a491e2e93e0f.png)

**Comment by aroumeliotis** [comment]
ok, sorry, I misread the title... Start minimized is what I'm looking for. I have keeweb running at startup and it's rather annoying to get its big window in front for no reason :) Anyway, thanks for your answer to my initial stupid question, I hope my actual question is not equally stupid...

**Comment by BWPanda** [comment]
@aroumeliotis I believe this would be the issue to follow for that request: https://github.com/keeweb/keeweb/issues/448
