### ISSUE TITLE
KeePassX kdb files support

### ISSUE THREAD

**Issue by iddqdidkfa** [antelle/keeweb#52]
I cannot open database saved with KeePassX. Is there any plans to support this format?

**Comment by antelle** [comment]
No, binary v1 files are not planned.
Tip: KeePassX now can work with kdbx files, you can just convert it.

**Comment by iddqdidkfa** [comment]
@antelle According to https://www.keepassx.org/faq KeePassX cant work with kdbx files. I have no option to convert in my Linux KeePassX Client.

**Comment by antelle** [comment]
v2 beta can work with kdbx: https://www.keepassx.org/news/
You can convert them with KeePass (I've managed to run it under mono on Mac, I think on linux it can be run as well).
