### ISSUE TITLE
Remove Demo functionality from desktop app

### ISSUE THREAD

**Issue by ismail** [antelle/keeweb#53]
Demo functionality does make sense for the web app (to some extent) but it doesn't really make sense on Desktop. No other desktop app has a demo mode.

**Comment by antelle** [comment]
1Password has it.
Yes, Demo button should be not completely removed but hidden deep once the user has successfully created or opened a db and made some action.

**Comment by alazare619** [comment]
if settings file exists a option to disable would be sufficient.

**Comment by Sigmanor** [comment]
Demonstration mode looks cool. Imho, demo button must be hidden after the first viewing.

**Comment by antelle** [comment]
Yes, it will be hidden and available with other storage providers, in a popup opened by "..." button.
On first launch, the app will show Demo button on the welcome screen.

**Comment by antelle** [comment]
Done, in v1.1 Demo button will be hidden, once the user has triggered it.
