### ISSUE TITLE
[Feature request] autocomplete usernames

### ISSUE THREAD

**Issue by jdbrice** [antelle/keeweb#54]
I didn't see any other feature request that covered this but i might have missed:

Add auto complete to the username field for new entries. I have a lot of different accounts that all use the same email as the username. It would be nice if after the first time entering it would autocomplete for subsequent entries.

It is a small thing but especially when migrating in a lot of accounts all at once it would be nice. Good job on the app.

**Comment by antelle** [comment]
:+1:

**Comment by antelle** [comment]
Fixed in 191de578a599fc97b2963fc1d5ac5388cc83f35a, uploaded to [beta.keeweb.info](https://beta.keeweb.info)
