### ISSUE TITLE
Firefox visual glitches

### ISSUE THREAD

**Issue by ProgMaq** [antelle/keeweb#55]
File, Created, Update and History fields move to the right of the screen (to disappear) when you move the mouse.

Firefox 42.0

![animation](https://cloud.githubusercontent.com/assets/3225856/11588871/fcdbbdb4-9a83-11e5-8053-cd8c0e1729fc.gif)

**Comment by antelle** [comment]
Only FF/Win

**Comment by antelle** [comment]
This was a weird bug in custom scrollbar Diokuz/baron#91, I've added some workarounds for it. Thanks for reporting! Will be merged in v5.
