### ISSUE TITLE
[Feature request] Hide empty or particular fields

### ISSUE THREAD

**Issue by paul-alkhimov** [antelle/keeweb#58]
In 99% cases I don't need to see any other text field except for "User" and "Password". It would be nice to have a checkbox in "Settings" to be able to hide all empty fields or maybe just to have the list of all text fields with checkboxes for each of them.
These are just my ideas, but the reason behind is that for every record I see a lot of trash on the screen instead of the necessary information (in my case I need only two fields, but your mileage may vary of course).

**Comment by antelle** [comment]
If empty fields are removed, there's no possibility to add them, since we don't have Edit/Save buttons. So, just auto-hiding empty is definitely not an option here.
Hide particular might be useful, configurable in settings.
Default 'Expires' field value ('Never') could be grayed in any case, there's no need in contrast color even all fields are shown.

**Comment by antelle** [comment]
v0.5 will not show value `Never` in `Expired` field anymore.
I have a solution which will allow hiding empty fields: next versions will have an option to hide empty fields in settings and `...` button in entry which will allow to add a custom or standard field, or perform other actions, like setup OTP.

**Comment by paul-alkhimov** [comment]
Is it implemented but not committed or just planned?

**Comment by antelle** [comment]
Disturbing value 'Never' in date field was removed and already released.
The rest is planned to [future](https://github.com/antelle/keeweb/wiki/TODO#future) (however backlog priority for Future have been estimated very roughly and is subject co change).
The UX is ready, now it's clear how to implement it.

**Comment by antelle** [comment]
So, it got implemented finally. You can preview the feature at https://beta.keeweb.info
`Entry Details` &rarr; `more...` &rarr; `Hide empty fields` will leave only used fields on the page, without any garbage. The only exception is for password: it will be always visible.

**Comment by kumabon** [comment]
May I ask why the exception to always display Password?

Personally, I have records (e.g. Membership #) with no password so it would be nice to have the field hidden as well.

I must also add that your implementation of record display is already miles ahead of your peer, especially with the custom fields all displayed together with standard ones without needing to switch tabs.
