### ISSUE TITLE
Site does not fit the window

### ISSUE THREAD

**Issue by p11sam1** [antelle/keeweb#59]
Hi, 

On the Lumia 950 XL (Windows 10 Mobile and Edge) KeeWeb does not fit inside the screen if the phone is held portrait. When on landscape it works fine.
![wp_ss_20151205_0001](https://cloud.githubusercontent.com/assets/15611561/11602876/7c615bd6-9ae6-11e5-9861-608e84c9d9ef.png)

**Comment by antelle** [comment]
This platform is not supported for now: https://github.com/antelle/keeweb/wiki/Supported-Platforms
I'll start working on Jan'16.
