### ISSUE TITLE
Change 'clicked' to 'click' event for appIcon

### ISSUE THREAD

**Issue by Desuvader** [antelle/keeweb#60]
Was reading your source code and noticed that you are using 'clicked' instead of 'click' here:
https://github.com/antelle/keeweb/blob/d4a69cab5122d4bba3b085257110b22ac5ed89b9/electron/app.js#L76

Not urgent, so I thought I'd just let you know :smile: 

Edit: Just to clarify for anyone reading. 'clicked' is getting deprecated.

**Comment by antelle** [comment]
Thanks!
