### ISSUE TITLE
Electron: not allowed to load local resource

### ISSUE THREAD

**Issue by Losiara** [antelle/keeweb#61]
Try run on ubuntu trusty.
Console logs:
Not allowed to load local resource: file:///home/....../tmp/index.html

**Comment by antelle** [comment]
Did you use the latest distribution or just run electron as electron-prebuilt? The latest app version works on Ubuntu 15.

**Comment by Losiara** [comment]
npm install electron-prebuilt -g

**Comment by antelle** [comment]
You should first build it, then run:
https://github.com/antelle/keeweb#building

**Comment by Losiara** [comment]
Sorry. My mistake.)

**Comment by antelle** [comment]
Feel free to reopen if it doesn't run after building

**Comment by Losiara** [comment]
All right. But maybe better to update docs. To clarify building with grunt before running on electron.

**Comment by antelle** [comment]
Yeah, thanks for pointing that. Readme says 'without building', which is wrong, I'll fix that: should be 'without building installer'.
