### ISSUE TITLE
Allow empty password of kdbx file.

### ISSUE THREAD

**Issue by Losiara** [antelle/keeweb#62]
I understand that unsafe, but sometimes helpfull.

**Comment by antelle** [comment]
:+1:  this is also a must for upcoming v0.5, as the app will save new files which have no password until the user assigns the password

**Comment by antelle** [comment]
Hm, you can already open files on current version

**Comment by Losiara** [comment]
Yes thats it also my bug. Sorry for divert.

**Comment by antelle** [comment]
But saving them results in error. It makes sense, to replace it with a question 'do you really want an empty password?'.

**Comment by antelle** [comment]
I'll reopen it to add a question
