### ISSUE TITLE
Auto-save changes at exit if it's enabled and add Save option to close dialog

### ISSUE THREAD

**Issue by Sigmanor** [antelle/keeweb#65]
Hi! There is a couple of  Issues to the new release. (I'm sorry that here is the two issues in one, but I don't think I need to open 2 issues for that).

1) Text **"You have unsaved files, all changes will be lost"** is uneven. (I think it is not fatal, but still)
2) After clicking **[X]** It would be logical add the another button: **"Save and exit"**.

![Screenshot](http://i.imgur.com/8VAN51X.png)

**Comment by antelle** [comment]
:+1:  Yeah, _Save at exit_ option makes sense in desktop apps (unlike web, where we cannot save anything on exit). I've forgot about this, will be added. Auto-save at exit is a must, especially now, when there's _auto save_ option in app settings.
