### ISSUE TITLE
Broken ''Select a key file" in Firefox

### ISSUE THREAD

**Issue by Matthaiks** [antelle/keeweb#66]
Hi!
Clicking "Select a key file" doesn't do anything.
Firefox 43 and KeeWeb v0.5.0

**Comment by antelle** [comment]
Can't reproduce: https://monosnap.com/file/LpNTCZmSltBYg9ZV8EwdqYaG5JUzeW
Please, specify more details: user-agent (available in settings/help), more detailed steps, some screenshots...

**Comment by Matthaiks** [comment]
This one:
![keeweb 2015 12 15 18-21-25](https://cloud.githubusercontent.com/assets/3577122/11818119/d8cdbe9e-a358-11e5-8027-0f6f1f39ff71.png)

**Comment by antelle** [comment]
Thanks, this doesn't work

**Comment by antelle** [comment]
Release updated; now should work

**Comment by Matthaiks** [comment]
Thanks!
