### ISSUE TITLE
Url display without HTTP

### ISSUE THREAD

**Issue by antelle** [antelle/keeweb#68]
We should display http:// urls without http:// prefix, so all urls will look identically

**Comment by paul-alkhimov** [comment]
For some sites (amazon, adobe etc.) the URL is very long and makes the window look really bad as it has no scrolling.
Is it possible either to show only domain part of the URL or maybe to wrap the long URL on the multiple lines?

**Comment by antelle** [comment]
Yes, it should be truncated, of course. Also related #67
