### ISSUE TITLE
A problem with a key file from Dropbox when self-hosting

### ISSUE THREAD

**Issue by Matthaiks** [antelle/keeweb#71]
Syncing with Dropbox works fine, but the Chooser does not. I'm getting this error from Dropbox: {"error": "Origin does not match any app domain"}.

KeeWeb v0.5.1 (73bbaf7, 2015-12-15)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by antelle** [comment]
Have you changed the app key? Which url is opened in chooser popup (I'm interested in app_key query parameter)?

**Comment by Matthaiks** [comment]
Yes. The app key is correct.

**Comment by antelle** [comment]
Have you added your domain in Dropbox app chooser domains list?
![developers - dropbox 2015-12-20 20-28-25](https://cloud.githubusercontent.com/assets/633557/11919034/53ad9960-a758-11e5-80e0-482ff74cbdf2.png)

**Comment by Matthaiks** [comment]
Yes, but only the LAN adress. I'm using KeeWeb only on my local network.

**Comment by antelle** [comment]
Something is strange here. Please, paste the url of popup which you get after clicking a button.

**Comment by Matthaiks** [comment]
https://www.dropbox.com/chooser?origin=https%3A%2F%2F192.168.1.5%3A777&app_key=***************&link_type=direct&trigger=js&multiselect=false&extensions=&folderselect=false&iframe=false&version=2

The app key is censored. ;-)

**Comment by antelle** [comment]
So, you have 192.168.1.5 added to Dropbox chooser/saver domains list, right?
Where in the app do you see the error?

**Comment by antelle** [comment]
I've just checked it and recorded a video: https://monosnap.com/file/Kzef7c9zT98zwSA8jdkzSilczms1py

**Comment by Matthaiks** [comment]
The adress is https://192.168.1.5:777/
The error shows up in the new tab.
I've just added https://localhost:777/ to Dropbox and it's working partially now. The tab opens up with the error and the https%3A%2F%2F192.168.1.5%3A777 adress in the URL. But changing it manually to https%3A%2F%2Flocalhost%3A777 loads the Chooser.

**Comment by antelle** [comment]
> I've just added https://localhost:777/

Sorry but you cannot add URL to that field, it accepts only domains.
Are you sure you are using Chooser/Saver domain and not Redirect URIs? These are different settings.

![developers - dropbox 2015-12-20 21-05-03](https://cloud.githubusercontent.com/assets/633557/11919218/5d40f2ec-a75d-11e5-95a0-df0a993504e1.png)

**Comment by Matthaiks** [comment]
Oops. I've missed that. So no Chooser for LAN?

**Comment by antelle** [comment]
Just add 192.168.1.5 to Chooser/Saver domain (as shown in my video above)

**Comment by Matthaiks** [comment]
Yes, now it's working. Sorry for the trouble!
