### ISSUE TITLE
Ctrl+A (select all) does not work.

### ISSUE THREAD

**Issue by paul-alkhimov** [antelle/keeweb#74]
I cannot select the complete text in the input field.
Normally I press Ctrl+A and then type something different, but here I have to erase the complete text letter-by-letter with backspace. It annoys and gives a feeling of the broken UI as Ctrl+A works everywhere else.

KeeWeb v0.5.1 (73bbaf7, 2015-12-15)
Environment: web
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by antelle** [comment]
Other text editing shortcuts, like alt/cmd/ctrl+arrows, should work as well
