### ISSUE TITLE
[FR] Lock interface after amount of time or after password copy

### ISSUE THREAD

**Issue by HazCod** [antelle/keeweb#75]
For web and/or desktop application.

**Comment by antelle** [comment]
Locking by amount of time is already here (Settings / General / Function / Auto-lock if the app is inactive). Locking after password copy may be added...

**Comment by antelle** [comment]
Added an option to lock on password copy, you can preview it at https://beta.keeweb.info/

**Comment by HazCod** [comment]
Looks good, thanks!

**Comment by antelle** [comment]
you may not close issues, they will be closed automatically once the code is merged to master branch
