### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by maxkfranz** [antelle/keeweb#76]
Using your github-pages account gives easy deployment and HTTPS support, but a shorter address would be nice.

keeweb.com is taken, but what about keeweb.co?

**Comment by Sigmanor** [comment]
Or keeweb.io

**Comment by antelle** [comment]
So, the app is now available here:
http://app.keeweb.info - the app itself, will redirect to github repo pages as it's https
http://keeweb.info - app website, under construction for now, will be created in a week or so
I've chosen .info because keepass has .info as well and .io is 3x more expensive.

**Comment by maxkfranz** [comment]
Great!

**Comment by antelle** [comment]
Bad part that the redirect still lacks HTTPS support (so the redirect app.keeweb.info is vulnerable to mitm attack), I'm thinking how to solve it...

**Comment by maxkfranz** [comment]
You should be able to have HTTPS on all keyweb.info URLs if you use a custom domain on Github pages: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by antelle** [comment]
Unfortunately, no. If I want to use HTTPS on custom domain, I have to use some proxy like cloudflare. There's no option to use HTTPS directly with github pages...

**Comment by maxkfranz** [comment]
You're right.  Might be better to use something other than Github pages then

**Comment by antelle** [comment]
Something other using HTTPS is either expensive or slow. I'm thinking about cloudfront... if the price will be no more than $0.5/month, I'll witch to it.

**Comment by maxkfranz** [comment]
That's what I would recommend, too.  Amazon's pricing is pretty unclear, though.  Probably best to just use the free period as an estimate.

**Comment by antelle** [comment]
Hm, for me, they looks rather clear: number or requests + traffic in gb/month + dns. My free period was finished several years ago... I have a couple of websites and a commercial project there, what I'm trying to estimate is traffic per month. Kind of marketing stuff, not technical, this is hard for me.

**Comment by antelle** [comment]
I've decided to use CloudFlare free plan, for now it should do the job very well.
So the website now has https: https://keeweb.info/ - and the app is available as https://app.keeweb.info/
I'm updating the links and adding support for Dropbox, tomorrow everything will be ready, together with DNS propagation.

**Comment by eligrey** [comment]
@antelle It doesn't seem wise to use unvalidated TLS for an online password manager. You should get your own certificates and change your hosting provider.
