### ISSUE TITLE
Disabling autoupdate for distro package

### ISSUE THREAD

**Issue by fthiery** [antelle/keeweb#78]
Hello,

I created an Arch Linux package here: https://aur.archlinux.org/packages/keeweb-desktop/

It copies all the zip contents to /usr/share/keeweb-desktop ; how is the the "Update" feature supposed to work (set to "Download and install automatically") ? Should i try to disable this in my package -- if that's possible -- or won't it cause any harm ?

**Comment by antelle** [comment]
Hello,
Thanks for creating it! :gift: 
> how is the the "Update" feature supposed to work

It downloads updated HTML/JS files and replaces them in user's app folder.
This is unacceptable for package manager, I guess. 
How can we implement auto-update disable in this case? I see a couple of options:
- create a special config file and if it's set, app will not auto-update and will not show update option in settings
- start the app with special parameter
Anything else? How is this typically implemented?

I have no experience of desktop app distribution under linux, so I may be missing something and need some help with best practices...

**Comment by fthiery** [comment]
I think that the easiest would be for your app to test if the running folder (in my case, /usr/share/keeweb-desktop) is write-enabled; if read-only, just grey out the feature and disable it.

**Comment by antelle** [comment]
The app saves updates in appdata folder which is writable on each system. The app folder itself is not writable.

**Comment by fthiery** [comment]
I don't know how other software does; maybe add a switch to the command, that's nicer than dropping a file somewhere imho.

**Comment by antelle** [comment]
The switch can be easily added indeed. Will the user be able to run the app without specifying this switch easily? E.g. on Windows a shortcut can be created which will point to the app + command-line switch. Is this available on Arch Linux and can this be created automatically during install? 
Hm, but this requires additional file creation again and, I believe, there will be troubles when files are 'Opened with' this app... not so good. Is writing a config file from setup really a bad option? E.g. on Windows, setup programs often preconfigure apps, create registry keys, files, ...

**Comment by fthiery** [comment]
With my approach, yes, because i drop a launcher shell script in /usr/bin, so basically it will always pass on the switch.

**Comment by fthiery** [comment]
Writing a config file is not necessarily a bit problem either btw

**Comment by antelle** [comment]
> i drop a launcher shell script in /usr/bin, so basically it will always pass on the switch

Am I correct with the following?

- the default action when the user launches the app from standard gui (some icon in gui, e.g. when I search apps in ubuntu menu) will be your startup script
- 'open with...' command for files will result in invoking the app with the switch as well
- there will be no other way for the user to start the app without the switch, unless he does it in some unusual way (e.g. go to app folder, find and start it)

**Comment by fthiery** [comment]
Yes, you are mostly correct; since the script that launches your app with the switch is dropped into /usr/bin, which is in the standard PATH environment variable, it's the only one that will be run from cmd line (by typing KeeWeb). Also, the desktop icon calls the same command that is in the PATH. 

However, user could still run the original app by using the absolute path (/opt/keeweb-desktop/KeeWeb).

**Comment by antelle** [comment]
Ok, the parameter will be added after v1 version. Related: #27

**Comment by antelle** [comment]
I've added `--disable-updater` option, it will be released in upcoming v1.0. If the app is launched with it, it will never check for updates and hide Update block in settings. Once launched without this option, the app will check for updates and the user will be able to install it - so please test carefully and ensure that the app is *never* launched without it by any default action the user can invoke (e.g. searching the app and launching it must use the option with this key). If you don't confirm it and app *could* be launched, please let me know and we'll resolve it, e.g. by creating a config file with this setting to disable it permanently.

**Comment by fthiery** [comment]
Done: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keeweb-desktop#n37

It's already launching with the argument.

**Comment by antelle** [comment]
Thank you!

**Comment by fthiery** [comment]
Thanks, it works as expected.
