### ISSUE TITLE
Proxy setting for auto-update desktop app.

### ISSUE THREAD

**Issue by Rurik19** [antelle/keeweb#79]
Behind proxy autoupdating doesn't work.

**Comment by antelle** [comment]
In upcoming v1.0 release the app will use proxy settings from system-wide config. If you want to use custom setting for this app, start it with `--proxy-server` command-line switch.

**Comment by nerddan** [comment]
By "system-wide config" do you mean environmanet variable `$https_proxy`?

**Comment by antelle** [comment]
@nerddan depends. On macOS and Windows, it's configured in GUI. Not sure if https_proxy will work on Linux in Electron, maybe.
