### ISSUE TITLE
Please enable Dropbox file chooser to open kdbx file in arbitrary folder (self hosted app)

### ISSUE THREAD

**Issue by pietia7** [antelle/keeweb#81]
I store kdbx file in Applications/Keepass2Android folder and right now I can't get self hosted app to choose file in this location. I set it up to have access to whole Dropbox account but in this config it only shows files in main Dropbox folder without possibility to dive into particular folders.

**Comment by antelle** [comment]
Folder choosing interface will not be implemented as it requires to much efforts with low business value. Once we have flexible Dropbox settings with a possibility to set custom app id, default folder setting will be added as well so you will be able to use files from custom folder. This is planned for v1.1, with other providers like google drive.

**Comment by mkolber** [comment]
The "work-around" is to allow KeeWeb to create its own DropBox folder and move your kdbx there.  Mark 

    On Tuesday, February 2, 2016 5:40 AM, pietia7 <notifications@github.com> wrote:
 
 

 I store kdbx file in Applications/Keepass2Android folder and right now I can't get self hosted app to choose file in this location I set it up to have access to whole Dropbox account but in this config it only shows files in main Dropbox folder without possibility to dive into particular folders—

**Comment by grinsted** [comment]
I have the exact same issue. Do you have a simple hack that would allow me to hardcode the name of a  Dropbox folder..?

**Comment by antelle** [comment]
There's no simple workaround. v1.1 will have custom folders support, and (as it's rather frequent request), later versions might have graphical folder chooser.

**Comment by antelle** [comment]
Implemented on https://beta.keeweb.info
Settings &rarr; Dropbox &rarr; Full Dropbox or any folder &rarr; folder
