### ISSUE TITLE
Copy-pasting the password sometimes results in pasting dots instead of the password

### ISSUE THREAD

**Issue by fthiery** [antelle/keeweb#89]
It is possible to copy-paste the password without revealing it; when this happens, pasting the password is pasting the dots (•••••••••) instead of the actual password 

![copypaste](https://cloud.githubusercontent.com/assets/87642/13111728/b061b58a-d587-11e5-8e0d-e21c1f583ec2.png)

**Comment by antelle** [comment]
For now, the most convenient ways to copy the password are:
- clicking its title ('Password')
- pressing Cmd/Ctrl+C

**Comment by fthiery** [comment]
The best would be to disable highligting on encrypted fields; that way, the user wouldn't think of pasting it.

**Comment by antelle** [comment]
Yes, we can do in such way (hoever it would be better co copy the actual value).
