### ISSUE TITLE
selfhosting

### ISSUE THREAD

**Issue by msenturk** [antelle/keeweb#9]
Hi,

First of all thanks for the app
Can u provide more documentation about self hosting keeweb please or maybe someone share dockerfile for it.

Thanks...

**Comment by antelle** [comment]
I'll describe in in the readme. Self-hosting is extremely simple: 
1. download this html file: https://github.com/antelle/keeweb/blob/gh-pages/index.html
2. put it wherever you want, either on hosting, or just save to file
3. open in any browser 
4. that's it
No server or any kind of hosting is required, this is a single-page app.

**Comment by msenturk** [comment]
oh my bad I didn't read it through. thx for quick reply :+1:

**Comment by antelle** [comment]
I've [added](https://github.com/antelle/keeweb#self-hosting) a note about self-hosting to the readme, to make it more clear.
