### ISSUE TITLE
Drag-drop is is not working

### ISSUE THREAD

**Issue by antelle** [antelle/keeweb#90]

**Comment by adaugherity** [comment]
Oh good, I thought I was missing something!  (Well not good that the bug exists, but I felt stupid for a bit...)

Is there a way to restore something from trash or move between folders other than via drag & drop?

**Comment by antelle** [comment]
There's no other way. The fix is already building and will be uploaded in 5..10 minutes.

**Comment by antelle** [comment]
Please go to Settings and click Update. The bug is fixed and arrived.

**Comment by adaugherity** [comment]
Works now.  Amazingly quick fix! :+1:

**Comment by matteoipri** [comment]
It doesn't work for me in Safari on Yosemite, latest Safari.
It does work in Firefox and Chromium on the same computer.
I tried both the demo version at https://beta.keeweb.info/ and a self hosted version with docker.
How can I help?

**Comment by antelle** [comment]
Please write the steps to reproduce. Also it's better to open a new issue, don't comment a general 'everything is not working' issue.
Drag-drop is working in Safari for me.

**Comment by matteoipri** [comment]
ok, thanks
