### ISSUE TITLE
[Feature request] Shortcut to copy username

### ISSUE THREAD

**Issue by noiseme** [antelle/keeweb#92]
Hi, recently i used KeePassX on my mac with KeePass 1.x base. Now only KeeWeb :) Great product! Great work! But in KeePassX was one very useful (for my opinion) feature. Hotkey ⌘B for copy USER field. It was so fast: ⌘B, ⌘V for USER data copiying, and ⌘C, ⌘V for PASSWORD data copiyng. Now, I see in Help/Shortcuts ⌘C — copy password or selected field, but i cant't copy USERname, only password. How about idea to add new shortcut ⌘B for copy UserName field data, or add custom users shortcuts?

Great product, I love it so much! Have a nice day!

**Comment by noiseme** [comment]
Oh, just saw in previous feature-request: "To copy a username, or any other field in entry, click its title."
0_0 This is so easy, thanks!

**Comment by antelle** [comment]
Hello!

:+1: thanks for idea about username copy shortcut, I'll add it, to copy by keyboard faster.

Regarding save, please provide the following info: 
1. Is auto-save enabled in app settings?
2. Were the changes saved when you launch the app next time?

Please, don't name your issues as just `feature request` or `bug`, give it something meaningful, so the issue title would tell something about its content. If you found two unrelated bugs or features, feel free to open two issues.

**Comment by noiseme** [comment]
> Please, don't name your issues as just feature request or bug, give it something meaningful, so the issue title would tell something about its content. If you found two unrelated bugs or features, feel free to open two issues.

Ok! Thanks! Wish good future for your ideas and products! Awesome ^_^

**Comment by noiseme** [comment]
> Regarding save, please provide the following info: 
1. Is auto-save enabled in app settings?
2. Were the changes saved when you launch the app next time?

1. Yep! (see attach)
<img width="200" alt="2016-02-21 14 09 02" src="https://cloud.githubusercontent.com/assets/328129/13202250/1021ff82-d8a5-11e5-84c5-ee462657f06f.png">

2. Nope. I tried different ways. Button ⌘Q, or via menu KeeWeb/Quit, or click on Lock button in app, or click on red circle. All works and saves data only when i save file on my desktop. When i used dropbox sync, then ⌘Q quits without saving and warning.

**Comment by noiseme** [comment]
> antelle added this to the v1.x milestone 4 hours ago

KeeWeb didn't open v1.x on my mac - i upgraded to v2.x, theen KeePass works %)

**Comment by antelle** [comment]
> When i used dropbox sync, then ⌘Q quits without saving and warning

That's a bug, thanks, I'll take a look.
> KeeWeb didn't open v1.x on my mac - i upgraded to v2.x, theen KeePass works %)

Milestones have nothing with KDBX file version - it's planning tool, which means the time, when I'm planning to make the fix.

**Comment by noiseme** [comment]
>That's a bug, thanks, I'll take a look.

Ok :+1: 

>I'm planning to make the fix.

Great! Thx for fast response! Have a nice day!

**Comment by antelle** [comment]
Confirmed Dropbox issue, posted it separately: https://github.com/antelle/keeweb/issues/93
You can subscribe to it, to be notified of updates.

**Comment by antelle** [comment]
Added ⌘B shortcut, it will be available in v1.1 release, you can preview the new feature at https://beta.keeweb.info/

**Comment by noiseme** [comment]
Great! Thanks a lot! :+1 :100:
