### ISSUE TITLE
App quit doesn't trigger saving of files stored in Dropbox if there are unsaved changes

### ISSUE THREAD

**Issue by antelle** [antelle/keeweb#93]
From [here](https://github.com/antelle/keeweb/issues/92#issuecomment-186814076): 
> If i edit kdb file, and then closed it without saving  #(Dropbox sync), file closed witout warning about saving new data. Maybe, idea to add warning isn.t so bad?

> Were the changes saved when you launch the app next time?

> Nope. I tried different ways. Button ⌘Q, or via menu KeeWeb/Quit, or click on Lock button in app, or click on red circle. All works and saves data only when i save file on my desktop. When i used dropbox sync, then ⌘Q quits without saving and warning.

**Comment by noiseme** [comment]
Great! Thanks a lot!

**Comment by antelle** [comment]
I've fixed it, it will be merged and released once the next bug for v1.0.x is fixed.

**Comment by noiseme** [comment]
:+1:
