### ISSUE TITLE
No clear indication that the file is stored in cache

### ISSUE THREAD

**Issue by skoam** [antelle/keeweb#94]
Hey keeweb devs,

I really love your tool but I just lost some passwords today. The web version of keeweb (using the self hosted version) saves files only in the cache and does not change the local file - which is okay, but it's really dangerous to hide this hint in the settings.

After adding new entries I hit "ctrl+s" to save the file, which caused the status of the file to change to "saved". You can close the tool from that without ever having seen any hint that your local file was never changed. If you clear your cache or upload the file back to, e.g. owncloud, you're not aware that everything you just added to your file was just temporary.

Since it almost caused me to loose a new random 20 characters password today which I only recovered from another application, I think this issue is highly critical.

Thank you for your concern,
skoam

**Comment by skoam** [comment]
I don't want to think about passwords I created in the last weeks on different devices. This is insane.

**Comment by skoam** [comment]
Hitting "x" on the recent file list (login view) should also not destroy a complete file (if working with cached files is the only solution). Without a warning at all.

**Comment by antelle** [comment]
Hello,
what would be your proposal for this, where and when to show the warning?
For me, it's clear that none of web apps can save local files but yes it could be confusing for some users.

**Comment by skoam** [comment]
Yes, I think it's not actually a problem of the system but convenience-wise it can cause data loss.

I could imagine the following changes:

- When saving a file ctrl+s when a local file was opened, trigger downloading the file in addition / instead of saving the cached copy
- When removing a cached file by hitting "x", show a clear indication that the cache file will be removed and offer to download the file
- Add a hint/popup that states that the web version cannot save local files directly and offer to download the desktop app (there already is a hint for that, but you have to find it in the settings first)

**Comment by antelle** [comment]
The second option will solve all problems with data loss. To explain the user that he's editing local files, I'll also add an alert when opening such files.

**Comment by skoam** [comment]
This would be great! Thank you!

**Comment by antelle** [comment]
I've made a fix, the release is going to happen today, you can preview the changes here: https://beta.keeweb.info/
