### ISSUE TITLE
Open preferences by Command-Comma (,) leads to unlock database

### ISSUE THREAD

**Issue by isbad** [antelle/keeweb#95]
Open preferences by Command-Comma (,) and then "Return to app" leads to unlock desktop app with no password.

OS X El Capitan 10.11.3
KeeWeb v1.0.2

**Comment by antelle** [comment]
Just to make it clear: it leads to opening unlocked interface, without any file being unlocked, so it's a usability issue, not security one

**Comment by antelle** [comment]
will be fixed in the nearest release update with some other fixes

**Comment by isbad** [comment]
On the contrary previously selected database is unlocked (security one)

**Comment by antelle** [comment]
you're right, thanks
