### ISSUE TITLE
[FeatureRequest] Regenerate password button

### ISSUE THREAD

**Issue by isbad** [antelle/keeweb#96]
It would be nice to have regenerate password button since you ~~don't like~~ can't use some symbols

**Comment by isbad** [comment]
I mean button in Generate window but additional password field action/button would be great

**Comment by antelle** [comment]
:+1:

**Comment by antelle** [comment]
![keeweb 2016-02-23 09-46-21](https://cloud.githubusercontent.com/assets/633557/13243758/558c1b3e-da12-11e5-9013-afe600493292.png)

**Comment by isbad** [comment]
You'r doing great job, thank you!

**Comment by sondr3** [comment]
Would it be possible for it to work like 1Passwords or http://makemeapassword.org/, where it generates a "sentence" so to speak as a password? I vastly prefer it since it's easier to write :)

**Comment by antelle** [comment]
good idea, but for now, only pronounceable passwords are implemented (you can preview at https://beta.keeweb.info).
