### ISSUE TITLE
[FeatureRequest] Ability to exclude small L (I) and capital i (I)

### ISSUE THREAD

**Issue by isbad** [antelle/keeweb#97]
Could you please add an ability to exclude small L (I) and capital i (I) in any default state (checked/unchecked)? Similar to already existing option ("0Oo")

**Comment by antelle** [comment]
They are excluded. Are they generated for you if you uncheck this option? Then it's a bug.
Checkbox `0Oo` means this: `ambiguous: 'O0oIl'`

**Comment by isbad** [comment]
Sorry, my bad (label confusing). It works as expected
